import{prisma}from"../../database/prisma.js";import{AppError}from"../../shared/errors/app-error.js";import type{MessageInput,SatisfactionInput,TicketInput}from"./support.validation.js";
export class SupportService{
 async list(organizationId:string,archived:boolean){const now=new Date();const[tickets,customers,employees]=await Promise.all([prisma.supportTicket.findMany({where:{organizationId,deletedAt:archived?{not:null}:null},include:{customer:{select:{id:true,displayName:true,email:true}},assignedEmployee:{select:{id:true,firstName:true,lastName:true,jobTitle:true}},messages:{where:{deletedAt:null},orderBy:{createdAt:"asc"},include:{createdBy:{select:{firstName:true,lastName:true}}}}},orderBy:[{priority:"desc"},{createdAt:"desc"}]}),prisma.customer.findMany({where:{organizationId,deletedAt:null},select:{id:true,displayName:true},orderBy:{displayName:"asc"}}),prisma.employee.findMany({where:{organizationId,status:"ACTIVE",deletedAt:null},select:{id:true,firstName:true,lastName:true,jobTitle:true},orderBy:{firstName:"asc"}})]);const active=tickets.filter(ticket=>!["RESOLVED","CLOSED"].includes(ticket.status));const responded=tickets.filter(ticket=>ticket.firstRespondedAt);const resolved=tickets.filter(ticket=>ticket.resolvedAt);const ratings=tickets.filter(ticket=>ticket.satisfactionRating!==null);return{tickets,customers,employees,metrics:{open:active.length,unassigned:active.filter(ticket=>!ticket.assignedEmployeeId).length,overdue:active.filter(ticket=>(!ticket.firstRespondedAt&&ticket.responseDueAt&&ticket.responseDueAt<now)||(ticket.resolutionDueAt&&ticket.resolutionDueAt<now)).length,averageResponseHours:responded.length?responded.reduce((sum,ticket)=>sum+(ticket.firstRespondedAt!.getTime()-ticket.createdAt.getTime())/3600000,0)/responded.length:null,averageResolutionHours:resolved.length?resolved.reduce((sum,ticket)=>sum+(ticket.resolvedAt!.getTime()-ticket.createdAt.getTime())/3600000,0)/resolved.length:null,satisfaction:ratings.length?ratings.reduce((sum,ticket)=>sum+ticket.satisfactionRating!,0)/ratings.length:null}}}
 private async references(organizationId:string,input:TicketInput){const[customer,employee]=await Promise.all([prisma.customer.findFirst({where:{id:input.customerId,organizationId,deletedAt:null}}),input.assignedEmployeeId?prisma.employee.findFirst({where:{id:input.assignedEmployeeId,organizationId,status:"ACTIVE",deletedAt:null}}):null]);if(!customer)throw new AppError(404,"Customer was not found.","CUSTOMER_NOT_FOUND");if(input.assignedEmployeeId&&!employee)throw new AppError(404,"Assigned employee was not found.","EMPLOYEE_NOT_FOUND")}
 async create(organizationId:string,userId:string,input:TicketInput){await this.references(organizationId,input);const ticketNumber=`SUP-${Date.now().toString(36).toUpperCase()}-${crypto.randomUUID().slice(0,4).toUpperCase()}`;return prisma.supportTicket.create({data:{...input,assignedEmployeeId:input.assignedEmployeeId??null,organizationId,ticketNumber,createdById:userId,updatedById:userId,messages:{create:{organizationId,type:"SYSTEM_EVENT",body:"Ticket created",isCustomerVisible:false,createdById:userId}}},include:{customer:true,messages:true}})}
 async update(organizationId:string,userId:string,id:string,input:TicketInput){await this.references(organizationId,input);const current=await prisma.supportTicket.findFirst({where:{id,organizationId,deletedAt:null}});if(!current)throw new AppError(404,"Ticket was not found.","TICKET_NOT_FOUND");const now=new Date();return prisma.supportTicket.update({where:{id},data:{...input,assignedEmployeeId:input.assignedEmployeeId??null,resolvedAt:input.status==="RESOLVED"&&!current.resolvedAt?now:input.status==="OPEN"||input.status==="IN_PROGRESS"||input.status==="WAITING_CUSTOMER"?null:current.resolvedAt,closedAt:input.status==="CLOSED"&&!current.closedAt?now:input.status!=="CLOSED"?null:current.closedAt,updatedById:userId}})}
 async message(organizationId:string,userId:string,ticketId:string,input:MessageInput){const ticket=await prisma.supportTicket.findFirst({where:{id:ticketId,organizationId,deletedAt:null}});if(!ticket)throw new AppError(404,"Ticket was not found.","TICKET_NOT_FOUND");return prisma.$transaction(async tx=>{const message=await tx.ticketMessage.create({data:{organizationId,ticketId,type:input.type,body:input.body,isCustomerVisible:input.type!=="INTERNAL_NOTE",createdById:userId}});if(input.type==="AGENT_REPLY"&&!ticket.firstRespondedAt)await tx.supportTicket.update({where:{id:ticketId},data:{firstRespondedAt:new Date(),status:ticket.status==="OPEN"?"IN_PROGRESS":ticket.status,updatedById:userId}});return message})}
 async satisfaction(organizationId:string,userId:string,id:string,input:SatisfactionInput){const result=await prisma.supportTicket.updateMany({where:{id,organizationId,deletedAt:null,status:{in:["RESOLVED","CLOSED"]}},data:{satisfactionRating:input.rating,satisfactionComment:input.comment,updatedById:userId}});if(result.count!==1)throw new AppError(409,"Satisfaction can only be recorded for a resolved ticket.","TICKET_NOT_RESOLVED")}
 async archive(organizationId:string,userId:string,id:string){if((await prisma.supportTicket.updateMany({where:{id,organizationId,deletedAt:null},data:{deletedAt:new Date(),updatedById:userId}})).count!==1)throw new AppError(404,"Ticket was not found.","TICKET_NOT_FOUND")}
 async restore(organizationId:string,userId:string,id:string){if((await prisma.supportTicket.updateMany({where:{id,organizationId,deletedAt:{not:null}},data:{deletedAt:null,updatedById:userId}})).count!==1)throw new AppError(404,"Archived ticket was not found.","TICKET_NOT_FOUND")}
}
