import { prisma } from "../../database/prisma.js";
import { AppError } from "../../shared/errors/app-error.js";
import type { EnrollmentInput, ExecutionCompletionInput, SequenceInput } from "./follow-up-automation.validation.js";

export class FollowUpAutomationService {
  async overview(organizationId: string, actorUserId: string) {
    await this.processDue(organizationId, actorUserId);
    const [sequences, enrollments, executions, inquiries, customers] = await Promise.all([
      prisma.followUpSequence.findMany({ where: { organizationId, archivedAt: null }, include: { steps: { orderBy: { stepOrder: "asc" } }, _count: { select: { enrollments: true } } }, orderBy: { createdAt: "desc" } }),
      prisma.followUpEnrollment.findMany({ where: { organizationId }, include: { sequence: { select: { id: true, name: true } }, executions: { orderBy: { dueAt: "asc" } } }, orderBy: { createdAt: "desc" }, take: 100 }),
      prisma.followUpExecution.findMany({ where: { organizationId, status: { in: ["DUE", "AWAITING_APPROVAL"] } }, include: { enrollment: { include: { sequence: { select: { name: true } } } } }, orderBy: { dueAt: "asc" }, take: 100 }),
      prisma.inquiry.findMany({ where: { organizationId, deletedAt: null, status: { notIn: ["CONVERTED", "DISQUALIFIED", "SPAM"] } }, select: { id: true, contactName: true, subject: true }, orderBy: { createdAt: "desc" }, take: 100 }),
      prisma.customer.findMany({ where: { organizationId, deletedAt: null }, select: { id: true, displayName: true }, orderBy: { displayName: "asc" }, take: 100 }),
    ]);
    const inquiryNames = new Map(inquiries.map((item) => [item.id, `${item.contactName} · ${item.subject}`])); const customerNames = new Map(customers.map((item) => [item.id, item.displayName]));
    return { sequences, enrollments: enrollments.map((item) => ({ ...item, targetName: item.inquiryId ? inquiryNames.get(item.inquiryId) ?? "Archived inquiry" : customerNames.get(item.customerId ?? "") ?? "Archived customer" })), dueExecutions: executions.map((item) => ({ ...item, targetName: item.enrollment.inquiryId ? inquiryNames.get(item.enrollment.inquiryId) ?? "Inquiry" : customerNames.get(item.enrollment.customerId ?? "") ?? "Customer" })), inquiries, customers, metrics: { activeSequences: sequences.filter((item) => item.isActive).length, activeEnrollments: enrollments.filter((item) => item.status === "ACTIVE").length, due: executions.filter((item) => item.status === "DUE").length, awaitingApproval: executions.filter((item) => item.status === "AWAITING_APPROVAL").length } };
  }
  async saveSequence(organizationId: string, actorUserId: string, id: string | null, input: SequenceInput) {
    return prisma.$transaction(async (tx) => { const sequence = id ? await tx.followUpSequence.findFirst({ where: { id, organizationId, archivedAt: null } }) : null; if (id && !sequence) throw new AppError(404, "Follow-up sequence was not found.", "SEQUENCE_NOT_FOUND"); const record = sequence ? await tx.followUpSequence.update({ where: { id: sequence.id }, data: { name: input.name, description: input.description, isActive: input.isActive, stopOnResponse: input.stopOnResponse, stopOnWonDeal: input.stopOnWonDeal, updatedById: actorUserId } }) : await tx.followUpSequence.create({ data: { organizationId, name: input.name, description: input.description, isActive: input.isActive, stopOnResponse: input.stopOnResponse, stopOnWonDeal: input.stopOnWonDeal, createdById: actorUserId, updatedById: actorUserId } }); if (sequence && await tx.followUpEnrollment.count({ where: { sequenceId: record.id } })) { const existing = await tx.followUpSequenceStep.findMany({ where: { sequenceId: record.id }, orderBy: { stepOrder: "asc" } }); if (JSON.stringify(existing.map((item) => ({ stepOrder: item.stepOrder, delayMinutes: item.delayMinutes, channel: item.channel, title: item.title, messageTemplate: item.messageTemplate, requiresApproval: item.requiresApproval }))) !== JSON.stringify([...input.steps].sort((a,b)=>a.stepOrder-b.stepOrder))) throw new AppError(409, "Steps cannot be changed after enrollment. Create a new sequence version instead.", "SEQUENCE_HAS_ENROLLMENTS"); } else { await tx.followUpSequenceStep.deleteMany({ where: { sequenceId: record.id } }); await tx.followUpSequenceStep.createMany({ data: input.steps.map((item) => ({ ...item, organizationId, sequenceId: record.id })) }); } return tx.followUpSequence.findUnique({ where: { id: record.id }, include: { steps: { orderBy: { stepOrder: "asc" } } } }); });
  }
  async archiveSequence(organizationId: string, actorUserId: string, id: string) { if ((await prisma.followUpSequence.updateMany({ where: { id, organizationId, archivedAt: null }, data: { isActive: false, archivedAt: new Date(), updatedById: actorUserId } })).count !== 1) throw new AppError(404, "Follow-up sequence was not found.", "SEQUENCE_NOT_FOUND"); }
  async enroll(organizationId: string, actorUserId: string, input: EnrollmentInput) {
    const sequence = await prisma.followUpSequence.findFirst({ where: { id: input.sequenceId, organizationId, isActive: true, archivedAt: null }, include: { steps: { orderBy: { stepOrder: "asc" } } } }); if (!sequence) throw new AppError(404, "Active follow-up sequence was not found.", "SEQUENCE_NOT_FOUND");
    const inquiry = input.targetType === "INQUIRY" ? await prisma.inquiry.findFirst({ where: { id: input.targetId, organizationId, deletedAt: null } }) : null; const customer = input.targetType === "CUSTOMER" ? await prisma.customer.findFirst({ where: { id: input.targetId, organizationId, deletedAt: null } }) : null; if (!inquiry && !customer) throw new AppError(404, "Enrollment target was not found.", "FOLLOW_UP_TARGET_NOT_FOUND");
    const duplicate = await prisma.followUpEnrollment.findFirst({ where: { organizationId, sequenceId: sequence.id, status: "ACTIVE", ...(inquiry ? { inquiryId: inquiry.id } : { customerId: customer!.id }) } }); if (duplicate) throw new AppError(409, "This record is already active in the selected sequence.", "ALREADY_ENROLLED");
    const context = { contactName: inquiry?.contactName ?? customer?.displayName ?? "Customer", companyName: inquiry?.companyName ?? customer?.companyName ?? "", subject: inquiry?.subject ?? "Follow-up" }; const render = (text: string) => text.replaceAll("{contactName}", context.contactName).replaceAll("{companyName}", context.companyName).replaceAll("{subject}", context.subject); let cursor = new Date(); const executions = sequence.steps.map((step) => { cursor = new Date(cursor.getTime() + step.delayMinutes * 60000); return { step, dueAt: new Date(cursor) }; });
    return prisma.followUpEnrollment.create({ data: { organizationId, sequenceId: sequence.id, inquiryId: inquiry?.id ?? null, customerId: customer?.id ?? inquiry?.customerId ?? null, assignedUserId: actorUserId, nextStepAt: executions[0]?.dueAt ?? null, createdById: actorUserId, updatedById: actorUserId, executions: { create: executions.map(({ step, dueAt }) => ({ organizationId, stepId: step.id, status: "SCHEDULED", scheduledAt: new Date(), dueAt, renderedTitle: render(step.title), renderedMessage: render(step.messageTemplate) })) } }, include: { executions: true } });
  }
  async processDue(organizationId: string, actorUserId: string) {
    const enrollments = await prisma.followUpEnrollment.findMany({ where: { organizationId, status: "ACTIVE", nextStepAt: { lte: new Date() } }, include: { sequence: true, executions: { orderBy: { dueAt: "asc" } } }, take: 100 });
    for (const enrollment of enrollments) { let stopReason: string | null = null; if (enrollment.sequence.stopOnResponse && enrollment.inquiryId) { const inquiry = await prisma.inquiry.findFirst({ where: { id: enrollment.inquiryId, organizationId }, select: { firstRespondedAt: true, status: true } }); if (inquiry?.firstRespondedAt || (inquiry && ["CONVERTED", "DISQUALIFIED", "SPAM"].includes(inquiry.status))) stopReason = "Inquiry received a response or was closed."; } if (!stopReason && enrollment.sequence.stopOnWonDeal && enrollment.customerId && await prisma.deal.findFirst({ where: { organizationId, customerId: enrollment.customerId, stage: "WON", deletedAt: null } })) stopReason = "Customer has a won deal."; if (stopReason) { await prisma.$transaction([prisma.followUpEnrollment.update({ where: { id: enrollment.id }, data: { status: "STOPPED", stoppedAt: new Date(), stopReason, nextStepAt: null, updatedById: actorUserId } }), prisma.followUpExecution.updateMany({ where: { enrollmentId: enrollment.id, status: "SCHEDULED" }, data: { status: "SKIPPED", outcome: stopReason } })]); continue; } const execution = enrollment.executions.find((item) => item.status === "SCHEDULED" && item.dueAt <= new Date()); if (!execution) continue; const step = await prisma.followUpSequenceStep.findFirst({ where: { id: execution.stepId, organizationId } }); if (!step) continue; const status = ["WHATSAPP", "EMAIL"].includes(step.channel) || step.requiresApproval ? "AWAITING_APPROVAL" : "DUE"; const next = enrollment.executions.find((item) => item.status === "SCHEDULED" && item.id !== execution.id); await prisma.$transaction([prisma.followUpExecution.update({ where: { id: execution.id }, data: { status } }), prisma.followUpEnrollment.update({ where: { id: enrollment.id }, data: { nextStepAt: next?.dueAt ?? null, updatedById: actorUserId } }), prisma.notification.create({ data: { organizationId, recipientId: enrollment.assignedUserId, type: status === "AWAITING_APPROVAL" ? "APPROVAL_REQUIRED" : "FOLLOW_UP_DUE", title: execution.renderedTitle, message: status === "AWAITING_APPROVAL" ? `Review ${step.channel.toLowerCase()} draft before contacting the customer.` : execution.renderedMessage, sourceType: "FOLLOW_UP_EXECUTION", sourceId: execution.id, actionPath: "/dashboard?view=automation", createdById: actorUserId, updatedById: actorUserId } })]); }
  }
  async completeExecution(organizationId: string, actorUserId: string, id: string, input: ExecutionCompletionInput) { const result = await prisma.followUpExecution.updateMany({ where: { id, organizationId, status: { in: ["DUE", "AWAITING_APPROVAL"] } }, data: { status: "COMPLETED", completedAt: new Date(), completedById: actorUserId, outcome: input.outcome } }); if (result.count !== 1) throw new AppError(404, "Due follow-up action was not found.", "FOLLOW_UP_EXECUTION_NOT_FOUND"); const execution = await prisma.followUpExecution.findFirst({ where: { id, organizationId }, include: { enrollment: { include: { executions: true } } } }); if (execution && execution.enrollment.executions.every((item) => item.id === id || ["COMPLETED", "SKIPPED", "CANCELED"].includes(item.status))) await prisma.followUpEnrollment.update({ where: { id: execution.enrollmentId }, data: { status: "COMPLETED", nextStepAt: null, updatedById: actorUserId } }); await prisma.notification.updateMany({ where: { organizationId, sourceType: "FOLLOW_UP_EXECUTION", sourceId: id }, data: { deletedAt: new Date(), updatedById: actorUserId } }); }
  async cancelEnrollment(organizationId: string, actorUserId: string, id: string) { const result = await prisma.followUpEnrollment.updateMany({ where: { id, organizationId, status: "ACTIVE" }, data: { status: "CANCELED", stoppedAt: new Date(), stopReason: "Canceled manually.", nextStepAt: null, updatedById: actorUserId } }); if (result.count !== 1) throw new AppError(404, "Active enrollment was not found.", "ENROLLMENT_NOT_FOUND"); await prisma.followUpExecution.updateMany({ where: { organizationId, enrollmentId: id, status: { in: ["SCHEDULED", "DUE", "AWAITING_APPROVAL"] } }, data: { status: "CANCELED", outcome: "Enrollment canceled." } }); }
}
