import type { BusinessBrief } from "./workspace-agent-types";

const cash = (value: number, currency = "INR") => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 0 }).format(value);
const viewFor = (href: string) => href.startsWith("/finance") ? "finance" : href.startsWith("/projects") ? "projects" : href.startsWith("/crm") ? "crm" : href.includes("inquiries") ? "inquiries" : href.includes("sales") ? "sales" : href.includes("analysis") ? "analysis" : href.includes("governance") ? "governance" : "dashboard";

export function BusinessBriefView({ brief, loading, onNavigate, onRefresh }: { brief: BusinessBrief; loading?: boolean; onNavigate?: (view: string) => void; onRefresh?: () => void }) {
  return <section className="agent-management-view agent-operating-brief" aria-label="Today's operating brief" aria-busy={loading}>
    <header><div><p>Daily operating brief</p><h3>{brief.executiveSummary}</h3><span>Generated {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kolkata" }).format(new Date(brief.generatedAt))}</span></div><button type="button" disabled={loading} onClick={onRefresh}>{loading ? "Refreshing…" : "Refresh brief"}</button></header>
    {!brief.complete && <div className="agent-warning" role="status">Partial brief: {brief.coverageSummary.unavailable} unavailable, {brief.coverageSummary.forbidden} forbidden, {brief.coverageSummary.failed} failed.</div>}
    <section className="agent-brief-coverage" aria-label="Source coverage"><strong>{brief.coverageSummary.checked} sources checked</strong><span>{brief.comparisonPeriod}</span></section>
    <section className="agent-brief-priorities"><h3>Top priorities</h3>{brief.priorities.length ? brief.priorities.map((item, index) => <article key={item.key}><span className={`agent-alert-severity ${item.severity.toLowerCase()}`}>{item.severity}</span><div><small>Priority {index + 1} · {item.service.replaceAll("_", " ")}</small><strong>{item.title}</strong><p>{item.reason}</p><span>{item.value === undefined ? item.evidence : `${cash(item.value, item.currency)} · ${item.evidence}`}</span></div><button type="button" onClick={() => onNavigate?.(viewFor(item.href))}>Review</button></article>) : <p className="agent-empty-copy">{brief.complete ? "Nothing currently needs attention in the verified sources." : "No priority could be verified from the available sources."}</p>}</section>
    <section className="agent-brief-changes"><h3>Since the previous business day</h3><p>{brief.comparisonPeriod}</p>{brief.changes.length ? brief.changes.map((item) => <article key={item.key}><div><strong>{item.title}</strong><span>{item.service.replaceAll("_", " ")} · {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kolkata" }).format(new Date(item.occurredAt))}</span></div><button type="button" onClick={() => onNavigate?.(viewFor(item.href))}>Open</button></article>) : <p className="agent-empty-copy">No supported timestamped changes were found. Status-history comparison is unavailable where only current state exists.</p>}</section>
    <section className="agent-recommendations"><h3>Suggested safe next actions</h3>{brief.recommendations.length ? brief.recommendations.map((item) => <article key={`${item.title}:${item.href}`}><div><strong>{item.title}</strong><p>{item.reason}</p></div><button type="button" onClick={() => onNavigate?.(viewFor(item.href))}>Review</button></article>) : <p className="agent-empty-copy">No action is currently recommended.</p>}</section>
    <details><summary>Source coverage details</summary><ul>{brief.coverage.map((item) => <li key={item.source}><strong>{item.source}</strong>: {item.status.replaceAll("_", " ")}</li>)}</ul></details>
  </section>;
}
