import type { AgentItem, AgentSection, AgentToolResult } from "./workspace-agent-types";

const defaultPrompts = ["Check my business health", "Summarize revenue, expenses and profit", "Count all CRM customers", "What should I improve?", "How do I add a customer in CRM?"];
const cash = (value: number, currency = "INR") => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 0 }).format(value);
const availabilityText: Record<AgentToolResult["availability"], string> = { VERIFIED: "Verified organization data", NO_DATA: "No records found", UNAVAILABLE: "Service unavailable", FORBIDDEN: "Access not permitted", FAILED: "Could not be checked" };

function AgentToolCards({ results }: { results: AgentToolResult[] }) {
  return <div className="agent-tool-results">{results.map((result) => <section key={result.toolName} className={`agent-tool-result ${result.availability.toLowerCase()}`} aria-label={`${result.service} results`}><header><div><strong>{result.service.replaceAll("_", " ")}</strong><span>{availabilityText[result.availability]}</span></div>{result.totalCount !== undefined && <span>{result.truncated ? `Showing ${result.resultCount} of ${result.totalCount}` : `${result.resultCount} result${result.resultCount === 1 ? "" : "s"}`}</span>}</header>{result.period && <p>Reporting period: {result.period}</p>}{result.records.map((record) => <article key={`${record.type}:${record.id}`}><div><strong>{record.label}</strong>{record.status && <span className="agent-tool-status">{record.status.replaceAll("_", " ")}</span>}{record.reason && <p>{record.reason}</p>}<small>{[record.date ? new Date(record.date).toLocaleDateString("en-IN") : null, record.amount !== undefined ? cash(record.amount, record.currency ?? result.currency) : null].filter(Boolean).join(" · ")}</small></div>{record.href && <a href={record.href} aria-label={`Open ${record.label}`}>Open</a>}</article>)}</section>)}</div>;
}

function AgentAnswer({ item, compact, loading, onSend, onNavigate, onSection, onConfirm, onClarify }: {
  item: AgentItem; compact: boolean; loading: boolean; onNavigate?: (view: string) => void;
  onSend: (message: string) => void;
  onSection: (section: AgentSection) => void; onConfirm: (token: string, decision: "CONFIRM" | "CANCEL") => void; onClarify: (token: string, choice: number, label: string) => void;
}) {
  const output = item.output;
  return <div className="workspace-agent-answer"><header><span>✦</span><strong>Ask B² Brain</strong></header><p>{output.answer}</p>
    {output.reasoning && <div className="forecast-card"><strong>{output.reasoning.source === "REAL_AI" ? "AI-assisted analysis" : "Verified-data fallback"}</strong><span>Confidence: {output.reasoning.confidence.toLowerCase()}</span>{output.reasoning.conclusions.length > 0 && <ul>{output.reasoning.conclusions.map((value) => <li key={value}>{value}</li>)}</ul>}{output.reasoning.recommendations.length > 0 && <ol>{output.reasoning.recommendations.map((value) => <li key={`${value.action}:${value.reason}`}><strong>{value.action}</strong> — {value.reason} ({value.expectedImpact})</li>)}</ol>}{output.reasoning.missingData.map((value) => <p className="agent-warning" key={value}>{value}</p>)}{(output.reasoning.requiresConfirmation || output.reasoning.proposedToolActions.length > 0) && <p className="agent-warning">Suggested actions require your confirmation; none were executed automatically.</p>}</div>}
    {output.metrics?.length ? <div className="workspace-metric-grid">{output.metrics.map((metric) => <article key={metric.label}><span>{metric.label}</span><strong>{metric.value === null ? metric.availability === "FORBIDDEN" ? "No access" : "Unavailable" : metric.value}</strong></article>)}</div> : null}
    {output.toolResults?.length ? <AgentToolCards results={output.toolResults} /> : null}
    {output.confirmation && <div className="agent-confirmation"><strong>Review required</strong>{output.confirmation.preview.targetLabel && <p><b>Target:</b> {output.confirmation.preview.targetLabel}</p>}{output.confirmation.preview.name && <p>Name: {output.confirmation.preview.name}</p>}{output.confirmation.preview.phone && <p>Phone: {output.confirmation.preview.phone}</p>}{output.confirmation.preview.category && <p>Category: {output.confirmation.preview.category.replaceAll("_", " ")}</p>}{output.confirmation.preview.changes && <dl>{Object.entries(output.confirmation.preview.changes).map(([name, value]) => <div key={name}><dt>{name.replaceAll(/([A-Z])/g, " $1")}</dt><dd>{value}</dd></div>)}</dl>}{output.confirmation.preview.consequence && <p>{output.confirmation.preview.consequence}</p>}{output.confirmation.preview.externalEffect === false && <span className="agent-no-external-effect">No external action</span>}<small>Expires {new Date(output.confirmation.expiresAt).toLocaleString("en-IN")}</small><div><button type="button" disabled={loading} onClick={() => onConfirm(output.confirmation!.token, "CONFIRM")}>Confirm</button><button type="button" disabled={loading} onClick={() => onConfirm(output.confirmation!.token, "CANCEL")}>Cancel</button></div></div>}
    {output.actionResult && <div className="agent-action-result" role="status"><strong>{output.actionResult.status === "ALREADY_COMPLETED" ? "Already completed" : "Action completed"}</strong><p>{output.actionResult.label}</p><span>No external action occurred.</span><a href={output.actionResult.href}>Open record</a></div>}
    {output.setupAssessment && <section className="agent-setup-card" aria-label="Guided setup"><header><div><strong>Guided setup</strong><span>Verified workspace checks</span></div>{output.setupAssessment.counts && <span>{output.setupAssessment.counts.complete} complete · {output.setupAssessment.counts.actionRequired} need action{output.setupAssessment.counts.optional !== undefined ? ` · ${output.setupAssessment.counts.optional} optional` : ""}</span>}</header>{output.setupAssessment.steps.length ? <ol>{output.setupAssessment.steps.map((step, index) => <li key={step.key}><div><span>Step {index + 1}</span><strong>{step.name}</strong><small>{step.status.replaceAll("_", " ")}{step.optional ? " · Optional" : ""}{step.testMode ? " · Test Mode" : ""}</small></div><p>{step.why}</p><p>{step.customerMust}</p><a href={step.href}>Open setup</a></li>)}</ol> : <p>No supported setup action is currently required.</p>}<footer><button type="button" onClick={() => onSend("What is still missing from my setup?")}>Check again</button><button type="button" onClick={() => onSend("Exit setup mode")}>Exit setup</button></footer></section>}
    {output.clarification && <div className="agent-clarification"><strong>I need clarification before checking</strong>{output.clarification.resolvedDate && <p>Resolved date: {output.clarification.resolvedDate}</p>}<div>{output.clarification.choices.map((choice, index) => <button type="button" disabled={loading} key={`${choice.label}:${index}`} onClick={() => onClarify(output.clarification!.token, index, choice.label)}>{choice.label}</button>)}</div><p>You can also type a correction below. Choose “None of these” by describing what you meant.</p></div>}
    {output.health && <div className="health-card"><header><span>Business health</span><strong>{output.health.overall === null ? "Insufficient data" : `${output.health.overall}/100`}</strong></header>{output.health.components.map((component) => <article key={component.name}><div><strong>{component.name}</strong><span>{component.evidence}</span></div><b>{Math.round(component.score)}/100</b></article>)}{output.health.recommendations.length > 0 && <ol>{output.health.recommendations.map((value) => <li key={value}>{value}</li>)}</ol>}</div>}
    {output.finance && <div className="workspace-metric-grid"><article><span>Revenue</span><strong>{cash(output.finance.current.revenue, output.finance.currency)}</strong></article><article><span>Expenses</span><strong>{cash(output.finance.current.expenses, output.finance.currency)}</strong></article><article><span>Profit</span><strong>{cash(output.finance.current.profit, output.finance.currency)}</strong></article></div>}
    {output.forecast && <div className="forecast-card"><strong>Transparent forecast</strong><span>{output.forecast.method} · {output.forecast.dateRange} · {output.forecast.confidence.replaceAll("_", " ")}</span><p>Assumptions: {output.forecast.assumptions.join("; ")}</p></div>}
    {output.warnings?.map((warning) => <div className="agent-warning" key={warning}>{warning}</div>)}
    {output.records?.map((record) => <button className="agent-record-link" key={`${record.type}:${record.id}`} onClick={() => onNavigate?.("crm")}>Open {record.label} →</button>)}
    {output.escalation && <div className="agent-escalation"><strong>Escalated to B² Brain team</strong><span>{output.escalation.requestNumber} · {output.escalation.status.replaceAll("_", " ")}</span><button onClick={() => onNavigate?.("b2help")}>Track request</button></div>}
    {output.setup && <button className="agent-record-link" onClick={() => onNavigate?.("settings")}>Continue agent setup →</button>}
    {output.managementSection && !compact && <button className="agent-record-link" onClick={() => onSection(output.managementSection!)}>Open {output.managementSection === "brief" ? "Today’s Brief" : "Goals"} →</button>}
    <details><summary>Source and action details</summary><p>Authenticated organization context and assigned permissions were enforced by the backend. No organization ID was accepted from this message.</p>{output.reasoning?.evidence.map((source) => <p key={source.id}><strong>{source.label}:</strong> {source.value ?? "Unavailable"} · {source.period}</p>)}{output.reasoning?.assumptions.length ? <p>Assumptions: {output.reasoning.assumptions.join("; ")}</p> : null}</details>
  </div>;
}

export function WorkspaceAgentConversation({ items, loading, compact, prompts = defaultPrompts, onSend, onNavigate, onSection, onConfirm, onClarify }: {
  items: AgentItem[]; loading: boolean; compact: boolean; onSend: (message: string) => void;
  prompts?: string[];
  onNavigate?: (view: string) => void; onSection: (section: AgentSection) => void; onConfirm: (token: string, decision: "CONFIRM" | "CANCEL") => void; onClarify: (token: string, choice: number, label: string) => void;
}) {
  return <div className="workspace-agent-thread" aria-live="polite">{!items.length && !loading ? <div className="workspace-agent-welcome"><div>✦</div><h3>{compact ? "Start a new conversation" : "How can I help your business?"}</h3><p>{compact ? "Ask about your business health, finances, customers or priorities." : "I can analyse permitted data, explain B² Brain and perform explicit low-risk actions."}</p><div>{prompts.map((prompt) => <button key={prompt} onClick={() => onSend(prompt)}>{prompt}</button>)}</div></div> : items.map((item) => <article key={item.id} className="workspace-agent-exchange"><div className="workspace-user-message"><strong>You</strong><p>{item.message}</p></div><AgentAnswer item={item} compact={compact} loading={loading} onSend={onSend} onNavigate={onNavigate} onSection={onSection} onConfirm={onConfirm} onClarify={onClarify} /></article>)}{loading && <div className="workspace-agent-thinking" role="status"><span className="spinner dark" />Checking permitted organization data…</div>}</div>;
}

export function WorkspaceAgentComposer({ message, loading, compact, onMessage, onSend }: {
  message: string; loading: boolean; compact: boolean; onMessage: (message: string) => void; onSend: () => void;
}) {
  return <footer className="workspace-agent-composer"><label htmlFor={compact ? "agent-drawer-message" : "agent-workspace-message"}>Message Ask B² Brain</label><textarea id={compact ? "agent-drawer-message" : "agent-workspace-message"} rows={compact ? 2 : 3} value={message} onChange={(event) => onMessage(event.target.value)} placeholder="Ask about your business or request a safe action…" maxLength={4096} /><button type="button" disabled={loading || !message.trim()} onClick={onSend}>{loading ? "Working…" : "Send"}</button></footer>;
}
