CREATE TABLE "SchoolAcademicYear" ("id" UUID NOT NULL, "organizationId" UUID NOT NULL, "name" TEXT NOT NULL, "startsOn" TIMESTAMP(3) NOT NULL, "endsOn" TIMESTAMP(3) NOT NULL, "isCurrent" BOOLEAN NOT NULL DEFAULT false, "createdById" UUID NOT NULL, "updatedById" UUID NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "SchoolAcademicYear_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SchoolClass" ("id" UUID NOT NULL, "organizationId" UUID NOT NULL, "academicYearId" UUID NOT NULL, "name" TEXT NOT NULL, "code" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdById" UUID NOT NULL, "updatedById" UUID NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "SchoolClass_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SchoolSection" ("id" UUID NOT NULL, "organizationId" UUID NOT NULL, "classId" UUID NOT NULL, "name" TEXT NOT NULL, "room" TEXT, "capacity" INTEGER, "createdById" UUID NOT NULL, "updatedById" UUID NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "SchoolSection_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "SchoolAcademicYear_organizationId_name_key" ON "SchoolAcademicYear"("organizationId", "name");
CREATE INDEX "SchoolAcademicYear_organizationId_isCurrent_deletedAt_idx" ON "SchoolAcademicYear"("organizationId", "isCurrent", "deletedAt");
CREATE UNIQUE INDEX "SchoolClass_academicYearId_code_key" ON "SchoolClass"("academicYearId", "code");
CREATE INDEX "SchoolClass_organizationId_academicYearId_deletedAt_idx" ON "SchoolClass"("organizationId", "academicYearId", "deletedAt");
CREATE UNIQUE INDEX "SchoolSection_classId_name_key" ON "SchoolSection"("classId", "name");
CREATE INDEX "SchoolSection_organizationId_classId_deletedAt_idx" ON "SchoolSection"("organizationId", "classId", "deletedAt");
ALTER TABLE "SchoolAcademicYear" ADD CONSTRAINT "SchoolAcademicYear_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SchoolAcademicYear" ADD CONSTRAINT "SchoolAcademicYear_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SchoolAcademicYear" ADD CONSTRAINT "SchoolAcademicYear_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SchoolClass" ADD CONSTRAINT "SchoolClass_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SchoolClass" ADD CONSTRAINT "SchoolClass_academicYearId_fkey" FOREIGN KEY ("academicYearId") REFERENCES "SchoolAcademicYear"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SchoolClass" ADD CONSTRAINT "SchoolClass_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SchoolClass" ADD CONSTRAINT "SchoolClass_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SchoolSection" ADD CONSTRAINT "SchoolSection_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SchoolSection" ADD CONSTRAINT "SchoolSection_classId_fkey" FOREIGN KEY ("classId") REFERENCES "SchoolClass"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SchoolSection" ADD CONSTRAINT "SchoolSection_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SchoolSection" ADD CONSTRAINT "SchoolSection_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
