import { Router } from "express";
import { prisma } from "./database/prisma.js";
import { authRouter } from "./modules/auth/auth.routes.js";
import { organizationRouter } from "./modules/organizations/organization.routes.js";
import { membershipRouter } from "./modules/memberships/membership.routes.js";
import { roleRouter } from "./modules/roles/role.routes.js";
import { serviceRouter } from "./modules/services/service.routes.js";
import { platformRouter } from "./modules/platform/platform.routes.js";
import { customerRouter } from "./modules/customers/customer.routes.js";
import { crmEngagementRouter, engagementRouter } from "./modules/customer-engagement/engagement.routes.js";
import { notificationRouter } from "./modules/notifications/notification.routes.js";
import { agentRouter } from "./modules/agents/agent.routes.js";
import { projectRouter } from "./modules/projects/project.routes.js";
import { employeeRouter } from "./modules/employees/employee.routes.js";
import { dealRouter } from "./modules/sales/deal.routes.js";
import { financeRouter } from "./modules/finance/finance.routes.js";
import { catalogueRouter } from "./modules/catalogue/catalogue.routes.js";
import { orderRouter } from "./modules/orders/order.routes.js";
import { inventoryRouter } from "./modules/inventory/inventory.routes.js";
import { marketingRouter } from "./modules/marketing/marketing.routes.js";
import { dashboardRouter } from "./modules/dashboard/dashboard.routes.js";
import { analysisRouter } from "./modules/analysis/analysis.routes.js";
import { supportRouter } from "./modules/support/support.routes.js";
import { websiteRouter } from "./modules/websites/website.routes.js";
import { procurementRouter } from "./modules/procurement/procurement.routes.js";
import { calendarRouter } from "./modules/calendar/calendar.routes.js";
import { inquiryRouter } from "./modules/inquiries/inquiry.routes.js";
import { bridgeRouter, bridgeWebhookRouter } from "./modules/automation-bridge/bridge.routes.js";
import { whatsappAdminRouter, whatsappWebhookRouter } from "./modules/automation-bridge/whatsapp.routes.js";
import { publicWebsiteFormRouter, websiteFormAdminRouter } from "./modules/automation-bridge/website-form.routes.js";
import { stayRouter } from "./modules/stay/stay.routes.js";
import { voiceCallRouter } from "./modules/voice-calls/voice-call.routes.js";
import { governanceRouter } from "./modules/governance/governance.routes.js";
import { actionCentreRouter } from "./modules/action-centre/action-centre.routes.js";
import { salesWorkQueueRouter } from "./modules/sales-work-queue/sales-work-queue.routes.js";
import { followUpAutomationRouter } from "./modules/follow-up-automation/follow-up-automation.routes.js";
import { publicQuotationRouter, quotationRouter } from "./modules/quotations/quotation.routes.js";
import { paymentCollectionRouter } from "./modules/payment-collection/payment-collection.routes.js";
import { managedServiceDeskRouter } from "./modules/managed-services/managed-service.routes.js";
import { serviceRequestRouter } from "./modules/service-requests/service-request.routes.js";
import { schoolRouter } from "./modules/school/school.routes.js";
import { success } from "./shared/responses/api-response.js";

export const apiRouter = Router();

apiRouter.get("/health", async (_request, response) => {
  await prisma.$queryRaw`SELECT 1`;
  response.status(200).json(success({ server: "healthy", database: "connected" }));
});
apiRouter.use("/auth", authRouter);
apiRouter.use("/organizations", organizationRouter);
apiRouter.use("/memberships", membershipRouter);
apiRouter.use("/roles", roleRouter);
apiRouter.use("/services", serviceRouter);
apiRouter.use("/platform", platformRouter);
apiRouter.use("/customers", customerRouter);
apiRouter.use("/customers/:customerId/engagement", engagementRouter);
apiRouter.use("/crm", crmEngagementRouter);
apiRouter.use("/notifications", notificationRouter);
apiRouter.use("/agents", agentRouter);
apiRouter.use("/projects", projectRouter);
apiRouter.use("/employees", employeeRouter);
apiRouter.use("/deals", dealRouter);
apiRouter.use("/finance", financeRouter);
apiRouter.use("/catalogue", catalogueRouter);
apiRouter.use("/orders", orderRouter);
apiRouter.use("/inventory", inventoryRouter);
apiRouter.use("/marketing", marketingRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/analysis", analysisRouter);
apiRouter.use("/support", supportRouter);
apiRouter.use("/websites", websiteRouter);
apiRouter.use("/procurement", procurementRouter);
apiRouter.use("/calendar", calendarRouter);
apiRouter.use("/inquiries", inquiryRouter);
apiRouter.use("/automation-bridge", bridgeRouter);
apiRouter.use("/automation-bridge", whatsappAdminRouter);
apiRouter.use("/automation-bridge", websiteFormAdminRouter);
apiRouter.use("/webhooks/intake", bridgeWebhookRouter);
apiRouter.use("/webhooks/whatsapp", whatsappWebhookRouter);
apiRouter.use("/public/forms", publicWebsiteFormRouter);
apiRouter.use("/stay", stayRouter);
apiRouter.use("/voice-calls", voiceCallRouter);
apiRouter.use("/governance", governanceRouter);
apiRouter.use("/action-centre", actionCentreRouter);
apiRouter.use("/sales-work-queue", salesWorkQueueRouter);
apiRouter.use("/follow-up-automation", followUpAutomationRouter);
apiRouter.use("/quotations", quotationRouter);
apiRouter.use("/public/quotations", publicQuotationRouter);
apiRouter.use("/payment-collection", paymentCollectionRouter);
apiRouter.use("/managed-services", managedServiceDeskRouter);
apiRouter.use("/service-requests", serviceRequestRouter);
apiRouter.use("/school", schoolRouter);
