"use client";
import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/services/api-client";
import { useAuth } from "@/features/auth/auth-context";

const actions = [
  ["CRM_CUSTOMER_READ", "Read CRM customers"], ["CRM_FOLLOWUP_READ", "Read CRM follow-ups"],
  ["MESSAGE_DRAFT", "Draft messages"], ["CRM_ACTIVITY_CREATE", "Create CRM activities"],
  ["CRM_FOLLOWUP_CREATE", "Schedule CRM follow-ups"],
] as const;
type Status = "DRAFT" | "ACTIVE" | "PAUSED";
interface Agent { id: string; name: string; purpose: string; instructions: string | null; supportedService: "CRM"; status: Status; requiresApproval: boolean; allowedActions: string[]; dailyRunLimit: number; dailyContactLimit: number; _count: { runs: number }; }
interface Response { success: true; data: Agent[]; }
const blank = { name: "", purpose: "", instructions: "", supportedService: "CRM" as const, status: "DRAFT" as Status, requiresApproval: true, allowedActions: [] as string[], dailyRunLimit: 10, dailyContactLimit: 0 };

export function AgentManager() {
  const { session, authorizedRequest } = useAuth(); const [agents, setAgents] = useState<Agent[]>([]); const [form, setForm] = useState(blank); const [editingId, setEditingId] = useState<string | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const canManage = session?.membership.permissions.includes("AUTOMATION_MANAGE") ?? false;
  const load = useCallback(async () => { const response = await authorizedRequest<Response>("/agents"); setAgents(response.data); }, [authorizedRequest]);
  useEffect(() => { const task = window.setTimeout(() => void load().catch(() => setError("Unable to load agents.")), 0); return () => window.clearTimeout(task); }, [load]);
  function edit(agent: Agent) { setEditingId(agent.id); setForm({ name: agent.name, purpose: agent.purpose, instructions: agent.instructions ?? "", supportedService: agent.supportedService, status: agent.status, requiresApproval: agent.requiresApproval, allowedActions: agent.allowedActions, dailyRunLimit: agent.dailyRunLimit, dailyContactLimit: agent.dailyContactLimit }); setOpen(true); }
  function toggle(action: string) { setForm({ ...form, allowedActions: form.allowedActions.includes(action) ? form.allowedActions.filter((item) => item !== action) : [...form.allowedActions, action] }); }
  async function save() { setSaving(true); setError(""); try { await authorizedRequest(editingId ? `/agents/${editingId}` : "/agents", { method: editingId ? "PUT" : "POST", body: JSON.stringify(form) }); setOpen(false); setEditingId(null); setForm(blank); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to save agent."); } finally { setSaving(false); } }
  async function archive(id: string) { if (!window.confirm("Archive this agent definition?")) return; await authorizedRequest(`/agents/${id}`, { method: "DELETE" }); await load(); }
  return <section className="agent-manager"><header><div><p>Intelligence layer</p><h3>AI agent definitions</h3><span>Configuration only. These agents cannot execute actions yet.</span></div>{canManage && <button type="button" onClick={() => { setEditingId(null); setForm(blank); setOpen(true); }}>Create agent</button>}</header>{error && <div className="form-alert">{error}</div>}{agents.length === 0 ? <div className="agent-empty"><strong>No agents configured.</strong><span>Create an organization-owned definition when you are ready.</span></div> : <div className="agent-grid">{agents.map((agent) => <article key={agent.id}><div><span className={`agent-status ${agent.status.toLowerCase()}`}>{agent.status}</span><small>{agent.supportedService}</small></div><h4>{agent.name}</h4><p>{agent.purpose}</p><dl><div><dt>Actions</dt><dd>{agent.allowedActions.length}</dd></div><div><dt>Approval</dt><dd>{agent.requiresApproval ? "Required" : "Not required"}</dd></div><div><dt>Runs</dt><dd>{agent._count.runs}</dd></div></dl>{canManage && <footer><button type="button" onClick={() => edit(agent)}>Configure</button><button type="button" onClick={() => void archive(agent.id)}>Archive</button></footer>}</article>)}</div>}
  {open && <div className="agent-modal"><div className="agent-dialog"><header><div><p>Agent control</p><h3>{editingId ? "Configure agent" : "Create agent"}</h3></div><button type="button" onClick={() => setOpen(false)}>×</button></header><label><span>Name</span><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="CRM follow-up assistant" /></label><label><span>Purpose</span><textarea value={form.purpose} onChange={(event) => setForm({ ...form, purpose: event.target.value })} rows={2} placeholder="What should this agent accomplish?" /></label><label><span>Instructions</span><textarea value={form.instructions} onChange={(event) => setForm({ ...form, instructions: event.target.value })} rows={3} placeholder="Rules, tone, escalation instructions…" /></label><div className="agent-form-grid"><label><span>Status</span><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as Status })}><option value="DRAFT">Draft</option><option value="ACTIVE">Active configuration</option><option value="PAUSED">Paused</option></select></label><label><span>Daily run limit</span><input type="number" min="0" max="1000" value={form.dailyRunLimit} onChange={(event) => setForm({ ...form, dailyRunLimit: Number(event.target.value) })} /></label><label><span>Daily contact limit</span><input type="number" min="0" max="500" value={form.dailyContactLimit} onChange={(event) => setForm({ ...form, dailyContactLimit: Number(event.target.value) })} /></label></div><div className="agent-actions"><span>Allowed actions</span>{actions.map(([code, label]) => <label key={code}><input type="checkbox" checked={form.allowedActions.includes(code)} onChange={() => toggle(code)} />{label}</label>)}</div><label className="approval-toggle"><input type="checkbox" checked={form.requiresApproval} onChange={(event) => setForm({ ...form, requiresApproval: event.target.checked })} /><span><strong>Require human approval</strong><small>Future external or record-changing actions must wait for approval.</small></span></label><footer><button type="button" onClick={() => setOpen(false)}>Cancel</button><button type="button" disabled={saving || form.name.trim().length < 2 || form.purpose.trim().length < 10} onClick={() => void save()}>{saving ? "Saving…" : "Save agent"}</button></footer></div></div>}
  </section>;
}
