"use client";
import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/services/api-client";
import { useAuth } from "@/features/auth/auth-context";

const actions = [
  ["CRM_CUSTOMER_READ", "Read CRM customers"], ["CRM_FOLLOWUP_READ", "Read CRM follow-ups"],
  ["INQUIRY_READ", "Read matching inquiries"], ["INQUIRY_CLASSIFY", "Classify inquiries"],
  ["INQUIRY_ROUTE", "Recommend inquiry routing"], ["INQUIRY_RESPONSE_DRAFT", "Draft inquiry responses"],
  ["FINANCE_INVOICE_READ", "Read collectible invoices"], ["COLLECTION_PRIORITIZE", "Prioritize overdue collections"],
  ["COLLECTION_DRAFT", "Draft payment reminders"], ["COLLECTION_FOLLOWUP_REQUEST", "Request collection follow-ups"],
  ["MESSAGE_DRAFT", "Draft messages"], ["CRM_ACTIVITY_CREATE", "Create CRM activities"],
  ["VOICE_CALL_PLAN", "Prepare AI voice calls"], ["VOICE_CALL_REQUEST", "Request approved AI calls"],
  ["CRM_FOLLOWUP_CREATE", "Schedule CRM follow-ups"],
] as const;
type Status = "DRAFT" | "ACTIVE" | "PAUSED";
interface Agent { id: string; name: string; purpose: string; instructions: string | null; supportedService: "CRM" | "LEADS" | "FINANCE"; status: Status; requiresApproval: boolean; allowedActions: string[]; dailyRunLimit: number; dailyContactLimit: number; _count: { runs: number }; }
interface Response { success: true; data: Agent[]; }
interface Benchmark { agent: { id: string; name: string; status: Status }; engineVersion: string; fixtureType: string; metrics: { cases: number; passed: number; passRate: number; safetyCompliance: number; averageLatencyMs: number; p95LatencyMs: number } }
interface PreviewResult { runId: string; status: string; output: { type: string; priority: string; confidence: number; routingService: string; responseDraft: string | null; requiresApproval: boolean; externalActionPerformed: boolean; existingCustomerMatches: { id: string; displayName: string }[]; possibleDuplicateInquiries: { id: string; subject: string }[] } }
interface CollectionRun { runId: string; status: string; matched: boolean; reason?: string; invoice?: { invoiceNumber: string; customerName: string; currency: string; outstanding: number; daysOverdue: number; risk: string }; previousAttempts?: number; proposedMessage?: string | null; approvalId?: string; followUpId?: string; externalActionPerformed: boolean; paymentStatusChanged: boolean }
const blank = { name: "", purpose: "", instructions: "", supportedService: "LEADS" as "CRM" | "LEADS" | "FINANCE", status: "DRAFT" as Status, requiresApproval: true, allowedActions: ["INQUIRY_READ", "INQUIRY_CLASSIFY", "INQUIRY_ROUTE", "INQUIRY_RESPONSE_DRAFT"] as string[], dailyRunLimit: 10, dailyContactLimit: 0 };
const blankPreview = { source: "WEBSITE", contactName: "", subject: "", message: "", email: "", phone: "" };

export function AgentManager() {
  const { session, authorizedRequest } = useAuth(); const [agents, setAgents] = useState<Agent[]>([]); const [form, setForm] = useState(blank); const [editingId, setEditingId] = useState<string | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [benchmark, setBenchmark] = useState<Benchmark | null>(null); const [benchmarking, setBenchmarking] = useState(false); const [testingAgent, setTestingAgent] = useState<Agent | null>(null); const [previewForm, setPreviewForm] = useState(blankPreview); const [previewResult, setPreviewResult] = useState<PreviewResult | null>(null); const [collectionRun, setCollectionRun] = useState<CollectionRun | null>(null); const [runningCollection, setRunningCollection] = useState(false);
  const canManage = session?.membership.permissions.includes("AUTOMATION_MANAGE") ?? false;
  const load = useCallback(async () => { const response = await authorizedRequest<Response>("/agents"); setAgents(response.data); }, [authorizedRequest]);
  useEffect(() => { const task = window.setTimeout(() => void load().catch(() => setError("Unable to load agents.")), 0); return () => window.clearTimeout(task); }, [load]);
  function edit(agent: Agent) { setEditingId(agent.id); setForm({ name: agent.name, purpose: agent.purpose, instructions: agent.instructions ?? "", supportedService: agent.supportedService, status: agent.status, requiresApproval: agent.requiresApproval, allowedActions: agent.allowedActions, dailyRunLimit: agent.dailyRunLimit, dailyContactLimit: agent.dailyContactLimit }); setOpen(true); }
  function toggle(action: string) { setForm({ ...form, allowedActions: form.allowedActions.includes(action) ? form.allowedActions.filter((item) => item !== action) : [...form.allowedActions, action] }); }
  async function save() { setSaving(true); setError(""); try { await authorizedRequest(editingId ? `/agents/${editingId}` : "/agents", { method: editingId ? "PUT" : "POST", body: JSON.stringify(form) }); setOpen(false); setEditingId(null); setForm(blank); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to save agent."); } finally { setSaving(false); } }
  async function runBenchmark(id: string) { setBenchmarking(true); setError(""); try { const response = await authorizedRequest<{ success: true; data: Benchmark }>(`/agents/${id}/benchmark`, { method: "POST", body: JSON.stringify({ iterations: 25 }) }); setBenchmark(response.data); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to benchmark agent."); } finally { setBenchmarking(false); } }
  async function runPreview() { if (!testingAgent) return; setSaving(true); setError(""); try { const response = await authorizedRequest<{ success: true; data: PreviewResult }>(`/agents/${testingAgent.id}/preview-lead`, { method: "POST", body: JSON.stringify({ ...previewForm, email: previewForm.email || null, phone: previewForm.phone || null }) }); setPreviewResult(response.data); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to run agent preview."); } finally { setSaving(false); } }
  async function runCollection(id: string) { setRunningCollection(true); setCollectionRun(null); setError(""); try { const response = await authorizedRequest<{ success: true; data: CollectionRun }>(`/agents/${id}/run-collection`, { method: "POST", body: JSON.stringify({ invoiceId: null }) }); setCollectionRun(response.data); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to run collection agent."); } finally { setRunningCollection(false); } }
  async function archive(id: string) { if (!window.confirm("Archive this agent definition?")) return; await authorizedRequest(`/agents/${id}`, { method: "DELETE" }); await load(); }
  return <section className="agent-manager"><header><div><p>Intelligence layer</p><h3>Agent definitions & evaluation</h3><span>B²-owned agents can inspect verified organization data and prepare controlled work. External delivery remains approval-gated.</span></div>{canManage && <button type="button" onClick={() => { setEditingId(null); setForm(blank); setOpen(true); }}>Create agent</button>}</header>{error && <div className="form-alert">{error}</div>}{agents.length === 0 ? <div className="agent-empty"><strong>No agents configured.</strong><span>Create an organization-owned definition when you are ready.</span></div> : <div className="agent-grid">{agents.map((agent) => <article key={agent.id}><div><span className={`agent-status ${agent.status.toLowerCase()}`}>{agent.status}</span><small>{agent.supportedService}</small></div><h4>{agent.name}</h4><p>{agent.purpose}</p><dl><div><dt>Actions</dt><dd>{agent.allowedActions.length}</dd></div><div><dt>Approval</dt><dd>{agent.requiresApproval ? "Required" : "Not required"}</dd></div><div><dt>Runs</dt><dd>{agent._count.runs}</dd></div></dl>{canManage && <footer>{agent.supportedService === "FINANCE" ? <button type="button" disabled={runningCollection || agent.status !== "ACTIVE"} onClick={() => void runCollection(agent.id)}>{runningCollection ? "Running…" : "Run collection"}</button> : <button type="button" onClick={() => { setTestingAgent(agent); setPreviewForm(blankPreview); setPreviewResult(null); }}>Test agent</button>}<button type="button" disabled={benchmarking} onClick={() => void runBenchmark(agent.id)}>Benchmark</button><button type="button" onClick={() => edit(agent)}>Configure</button><button type="button" onClick={() => void archive(agent.id)}>Archive</button></footer>}</article>)}</div>}
  {collectionRun && <div className="agent-benchmark"><header><div><p>Collection agent result</p><h4>{collectionRun.matched ? `${collectionRun.invoice?.invoiceNumber} · ${collectionRun.invoice?.customerName}` : "No action required"}</h4></div><span>{collectionRun.status.replaceAll("_", " ")}</span></header>{collectionRun.matched && collectionRun.invoice ? <><div><article><small>Outstanding</small><strong>{collectionRun.invoice.currency} {collectionRun.invoice.outstanding.toFixed(2)}</strong></article><article><small>Overdue</small><strong>{collectionRun.invoice.daysOverdue} days</strong></article><article><small>Risk</small><strong>{collectionRun.invoice.risk}</strong></article><article><small>Previous attempts</small><strong>{collectionRun.previousAttempts ?? 0}</strong></article></div><p>{collectionRun.proposedMessage}</p><p>Approval and an internal follow-up were created. No message was sent and no payment record was changed.</p></> : <p>{collectionRun.reason === "FOLLOW_UP_ALREADY_PENDING" ? "Every overdue invoice already has a pending collection follow-up." : "No overdue collectible invoice was found for this organization."}</p>}</div>}
  {benchmark && <div className="agent-benchmark"><header><div><p>Evaluation result</p><h4>{benchmark.agent.name}</h4></div><span>{(benchmark.metrics.passRate * 100).toFixed(0)}% pass</span></header><div><article><small>Cases</small><strong>{benchmark.metrics.passed}/{benchmark.metrics.cases}</strong></article><article><small>Safety compliance</small><strong>{(benchmark.metrics.safetyCompliance * 100).toFixed(0)}%</strong></article><article><small>Average latency</small><strong>{benchmark.metrics.averageLatencyMs.toFixed(3)} ms</strong></article><article><small>P95 latency</small><strong>{benchmark.metrics.p95LatencyMs.toFixed(3)} ms</strong></article></div><p>{benchmark.engineVersion} · Evaluation fixtures only; no tenant business records were created.</p></div>}
  {testingAgent && <div className="agent-modal"><div className="agent-dialog"><header><div><p>Safe execution preview</p><h3>Test {testingAgent.name}</h3></div><button type="button" onClick={() => setTestingAgent(null)}>×</button></header><div className="agent-form-grid"><label><span>Source</span><select value={previewForm.source} onChange={(event) => setPreviewForm({ ...previewForm, source: event.target.value })}>{["WEBSITE", "WHATSAPP", "EMAIL", "PHONE", "SOCIAL", "MANUAL"].map((source) => <option key={source}>{source}</option>)}</select></label><label><span>Contact name</span><input value={previewForm.contactName} onChange={(event) => setPreviewForm({ ...previewForm, contactName: event.target.value })} /></label><label><span>Email</span><input type="email" value={previewForm.email} onChange={(event) => setPreviewForm({ ...previewForm, email: event.target.value })} /></label><label><span>Phone</span><input value={previewForm.phone} onChange={(event) => setPreviewForm({ ...previewForm, phone: event.target.value })} /></label></div><label><span>Subject</span><input value={previewForm.subject} onChange={(event) => setPreviewForm({ ...previewForm, subject: event.target.value })} /></label><label><span>Message</span><textarea rows={4} value={previewForm.message} onChange={(event) => setPreviewForm({ ...previewForm, message: event.target.value })} /></label>{previewResult && <div className="agent-preview-result"><strong>{previewResult.output.type} · {previewResult.output.priority}</strong><span>Route: {previewResult.output.routingService} · Confidence {(previewResult.output.confidence * 100).toFixed(0)}%</span><p>{previewResult.output.responseDraft ?? "No response draft produced."}</p><small>{previewResult.output.existingCustomerMatches.length} customer matches · {previewResult.output.possibleDuplicateInquiries.length} possible duplicates · External action performed: No</small></div>}<footer><button type="button" onClick={() => setTestingAgent(null)}>Close</button><button type="button" disabled={saving || previewForm.contactName.length < 2 || previewForm.subject.length < 2 || previewForm.message.length < 2 || (!previewForm.email && !previewForm.phone)} onClick={() => void runPreview()}>{saving ? "Running…" : "Run safe preview"}</button></footer></div></div>}
  {open && <div className="agent-modal"><div className="agent-dialog"><header><div><p>Agent control</p><h3>{editingId ? "Configure agent" : "Create agent"}</h3></div><button type="button" onClick={() => setOpen(false)}>×</button></header><label><span>Name</span><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Payment collection agent" /></label><label><span>Purpose</span><textarea value={form.purpose} onChange={(event) => setForm({ ...form, purpose: event.target.value })} rows={2} placeholder="What should this agent accomplish?" /></label><label><span>Instructions</span><textarea value={form.instructions} onChange={(event) => setForm({ ...form, instructions: event.target.value })} rows={3} placeholder="Rules, tone, escalation instructions…" /></label><div className="agent-form-grid"><label><span>Service</span><select value={form.supportedService} onChange={(event) => setForm({ ...form, supportedService: event.target.value as "CRM" | "LEADS" | "FINANCE", allowedActions: event.target.value === "FINANCE" ? ["FINANCE_INVOICE_READ", "COLLECTION_PRIORITIZE", "COLLECTION_DRAFT", "COLLECTION_FOLLOWUP_REQUEST"] : form.allowedActions })}><option value="LEADS">Leads & inquiries</option><option value="CRM">CRM</option><option value="FINANCE">Finance & collections</option></select></label><label><span>Status</span><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as Status })}><option value="DRAFT">Draft</option><option value="ACTIVE">Active configuration</option><option value="PAUSED">Paused</option></select></label><label><span>Daily run limit</span><input type="number" min="0" max="1000" value={form.dailyRunLimit} onChange={(event) => setForm({ ...form, dailyRunLimit: Number(event.target.value) })} /></label><label><span>Daily contact limit</span><input type="number" min="0" max="500" value={form.dailyContactLimit} onChange={(event) => setForm({ ...form, dailyContactLimit: Number(event.target.value) })} /></label></div><div className="agent-actions"><span>Allowed actions</span>{actions.map(([code, label]) => <label key={code}><input type="checkbox" checked={form.allowedActions.includes(code)} onChange={() => toggle(code)} />{label}</label>)}</div><label className="approval-toggle"><input type="checkbox" checked={form.requiresApproval} onChange={(event) => setForm({ ...form, requiresApproval: event.target.checked })} /><span><strong>Require human approval</strong><small>External or record-changing actions must wait for approval.</small></span></label><footer><button type="button" onClick={() => setOpen(false)}>Cancel</button><button type="button" disabled={saving || form.name.trim().length < 2 || form.purpose.trim().length < 10} onClick={() => void save()}>{saving ? "Saving…" : "Save agent"}</button></footer></div></div>}
  </section>;
}
