"use client";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/features/auth/auth-context";
import { ApiError } from "@/services/api-client";
type Agent = { id: string; name: string; status: string; supportedService: string; requiresApproval: boolean };
type Schedule = { id: string; enabled: boolean; timezone: string; localTime: string; maxInvoicesPerRun: number; nextRunAt: string; lastRunAt: string | null; lastStatus: string | null; lastError: string | null };
const initial = { enabled: true, timezone: "Asia/Kolkata", localTime: "09:00", maxInvoicesPerRun: 5 };
export function CollectionScheduleManager() {
  const { authorizedRequest, session } = useAuth();
  const [agents, setAgents] = useState<Agent[]>([]), [agentId, setAgentId] = useState(""), [schedule, setSchedule] = useState<Schedule | null>(null), [form, setForm] = useState(initial), [saving, setSaving] = useState(false), [notice, setNotice] = useState(""), [error, setError] = useState("");
  const canManage = session?.membership.permissions.includes("AUTOMATION_MANAGE") ?? false;
  const loadAgents = useCallback(async () => { const response = await authorizedRequest<{ success: true; data: Agent[] }>("/agents"); const finance = response.data.filter((item) => item.supportedService === "FINANCE"); setAgents(finance); setAgentId((current) => current || finance.find((item) => item.status === "ACTIVE")?.id || finance[0]?.id || ""); }, [authorizedRequest]);
  const loadSchedule = useCallback(async (id: string) => { if (!id) { setSchedule(null); return; } const response = await authorizedRequest<{ success: true; data: Schedule | null }>(`/agents/${id}/schedule`); setSchedule(response.data); setForm(response.data ? { enabled: response.data.enabled, timezone: response.data.timezone, localTime: response.data.localTime, maxInvoicesPerRun: response.data.maxInvoicesPerRun } : initial); }, [authorizedRequest]);
  useEffect(() => { const timer = setTimeout(() => void loadAgents().catch(() => setError("Unable to load collection agents.")), 0); return () => clearTimeout(timer); }, [loadAgents]);
  useEffect(() => { const timer = setTimeout(() => void loadSchedule(agentId).catch(() => setError("Unable to load collection schedule.")), 0); return () => clearTimeout(timer); }, [agentId, loadSchedule]);
  async function save() { setSaving(true); setError(""); setNotice(""); try { await authorizedRequest(`/agents/${agentId}/schedule`, { method: "PUT", body: JSON.stringify(form) }); setNotice(form.enabled ? "Daily collection schedule activated." : "Collection schedule paused."); await loadSchedule(agentId); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to save schedule."); } finally { setSaving(false); } }
  const selected = agents.find((item) => item.id === agentId);
  return <section className="collection-schedule-manager"><header><div><p>Scheduled intelligence</p><h3>Daily collection schedule</h3><span>Automatically inspect overdue invoices and prepare approval requests. Email delivery remains manual and approval-controlled.</span></div><i className={`agent-run-status ${schedule?.enabled ? "completed" : "canceled"}`}>{schedule ? schedule.enabled ? "ACTIVE" : "PAUSED" : "NOT CONFIGURED"}</i></header>{notice && <div className="dashboard-notice success">{notice}</div>}{error && <div className="form-alert">{error}</div>}{agents.length === 0 ? <div className="agent-run-empty"><strong>No Finance agent found</strong><span>Create an active Finance Collection Agent first.</span></div> : <><div className="schedule-form"><label><span>Collection agent</span><select value={agentId} onChange={(event) => setAgentId(event.target.value)}>{agents.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.status}</option>)}</select></label><label><span>Daily time</span><input type="time" value={form.localTime} onChange={(event) => setForm({ ...form, localTime: event.target.value })} /></label><label><span>Timezone</span><input value={form.timezone} onChange={(event) => setForm({ ...form, timezone: event.target.value })} /></label><label><span>Invoices per run</span><input type="number" min={1} max={25} value={form.maxInvoicesPerRun} onChange={(event) => setForm({ ...form, maxInvoicesPerRun: Number(event.target.value) })} /></label><label className="approval-toggle"><input type="checkbox" checked={form.enabled} onChange={(event) => setForm({ ...form, enabled: event.target.checked })} /><span><strong>Schedule enabled</strong><small>Pause without deleting configuration.</small></span></label>{canManage && <button disabled={saving || !agentId || selected?.status !== "ACTIVE" || !selected?.requiresApproval} onClick={() => void save()}>{saving ? "Saving…" : "Save schedule"}</button>}</div>{schedule && <div className="schedule-status"><article><small>Next run</small><strong>{new Date(schedule.nextRunAt).toLocaleString()}</strong></article><article><small>Last run</small><strong>{schedule.lastRunAt ? new Date(schedule.lastRunAt).toLocaleString() : "Not run yet"}</strong></article><article><small>Last result</small><strong>{schedule.lastStatus?.replaceAll("_", " ") ?? "Waiting"}</strong></article>{schedule.lastError && <p>{schedule.lastError}</p>}</div>}</>}</section>;
}
