import { createHash, randomBytes } from "node:crypto";
import { Prisma } from "@prisma/client";
import { prisma } from "../../database/prisma.js";
import { AppError } from "../../shared/errors/app-error.js";
import { decryptSecret, encryptSecret } from "./bridge.crypto.js";
import { FakeMetaLeadConnectionProvider, META_LEAD_REQUIRED_PERMISSIONS, type MetaLeadConnectionProvider, type MetaPageChoice } from "./meta-lead-provider.js";
import type { MetaConnectionCallbackInput, MetaConnectionStartInput, MetaFormSelectionInput, MetaPageSelectionInput } from "./meta-lead-connection.validation.js";

type Context = { organizationId: string; membershipId: string; userId: string };
type Config = { metaSetupMode?: "TEST"; metaSetupState?: string; metaAuthorizedPages?: Array<Omit<MetaPageChoice, "token">>; metaPageName?: string; metaVerifiedForms?: Array<{ id: string; name: string }>; metaLeadAllowedFormIds?: string[]; metaLeadAuthorizationVerified?: boolean; metaRequiredPermissionsValid?: boolean; metaSubscriptionVerified?: boolean; metaLastVerifiedAt?: string; metaLastTestAt?: string; metaTokenExpiresAt?: string; metaDisconnectedAt?: string };
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const connectorWhere = (context: Context, id: string) => ({ id, organizationId: context.organizationId, type: "SOCIAL" as const, provider: "META_LEAD_ADS", deletedAt: null, status: { not: "ARCHIVED" as const } });

export class MetaLeadConnectionService {
  constructor(private readonly provider: MetaLeadConnectionProvider = new FakeMetaLeadConnectionProvider()) {}
  async status(context: Context, connectorId: string) {
    const connector = await prisma.integrationConnector.findFirst({ where: connectorWhere(context, connectorId), select: { id: true, status: true, metaPageId: true, configuration: true, credentialsConfiguredAt: true, lastSuccessfulAt: true } });
    if (!connector) throw new AppError(404, "Connector was not found.", "CONNECTOR_NOT_FOUND");
    const c = connector.configuration as Config;
    const expired = Boolean(c.metaTokenExpiresAt && new Date(c.metaTokenExpiresAt) <= new Date());
    return { connectorId: connector.id, connectorStatus: connector.status, mode: this.provider.mode, setupState: expired ? "EXPIRED" : c.metaSetupState ?? "DRAFT", page: connector.metaPageId ? { name: c.metaPageName ?? "Meta Page", maskedId: `••••${connector.metaPageId.slice(-4)}` } : null, forms: (c.metaVerifiedForms ?? []).filter(form => c.metaLeadAllowedFormIds?.includes(form.id)).map(form => ({ id: form.id, name: form.name })), permissionsValid: !expired && Boolean(c.metaRequiredPermissionsValid), subscriptionVerified: !expired && Boolean(c.metaSubscriptionVerified), authorizationVerified: !expired && Boolean(c.metaLeadAuthorizationVerified), lastVerifiedAt: c.metaLastVerifiedAt ?? null, lastTestAt: c.metaLastTestAt ?? null, lastSuccessfulLeadAt: connector.lastSuccessfulAt, tokenExpiresAt: c.metaTokenExpiresAt ?? null, canActivateProduction: false };
  }
  async start(context: Context, connectorId: string, input: MetaConnectionStartInput) {
    await this.connector(context, connectorId);
    const state = randomBytes(32).toString("base64url"), returnPath = input.returnPath ?? "/automation", expiresAt = new Date(Date.now() + 10 * 60_000);
    await prisma.$transaction(async tx => {
      const stale = await tx.integrationAuthorizationState.findMany({ where: { OR: [{ expiresAt: { lt: new Date() } }, { consumedAt: { not: null }, createdAt: { lt: new Date(Date.now() - 86_400_000) } }], provider: "META_LEAD_ADS" }, select: { id: true }, take: 100 });
      if (stale.length) await tx.integrationAuthorizationState.deleteMany({ where: { id: { in: stale.map(item => item.id) } } });
      await tx.integrationAuthorizationState.create({ data: { stateHash: hash(state), provider: "META_LEAD_ADS", ...context, connectorId, returnPath, expiresAt } });
      await this.audit(tx, context, connectorId, "META_AUTHORIZATION_STARTED", "Meta Lead Ads test authorization started.");
    });
    return { authorizationUrl: this.provider.buildAuthorizationUrl(state, returnPath), expiresAt, mode: this.provider.mode };
  }
  async callback(context: Context, connectorId: string, input: MetaConnectionCallbackInput) {
    const now = new Date(), stateHash = hash(input.state);
    const authorization = await prisma.$transaction(async tx => {
      const consumed = await tx.integrationAuthorizationState.updateMany({ where: { stateHash, provider: "META_LEAD_ADS", ...context, connectorId, consumedAt: null, expiresAt: { gt: now }, organization: { status: "ACTIVE", deletedAt: null }, user: { status: "ACTIVE", deletedAt: null }, membership: { organizationId: context.organizationId, userId: context.userId, status: "ACTIVE" }, connector: connectorWhere(context, connectorId) }, data: { consumedAt: now } });
      if (consumed.count !== 1) throw new AppError(400, "Authorization state is invalid or expired.", "META_AUTHORIZATION_STATE_INVALID");
      return tx.integrationAuthorizationState.findUniqueOrThrow({ where: { stateHash }, select: { returnPath: true } });
    });
    let exchanged: Awaited<ReturnType<MetaLeadConnectionProvider["exchangeCode"]>>;
    try { exchanged = await this.provider.exchangeCode(input.code); }
    catch { await prisma.auditEvent.create({ data: { organizationId: context.organizationId, actorType: "USER", actorUserId: context.userId, serviceCode: "AUTOMATION", actionCode: "META_AUTHORIZATION_FAILED", sourceType: "INTEGRATION_CONNECTOR", sourceId: connectorId, summary: "Meta Lead Ads test authorization failed.", metadata: { provider: "META_LEAD_ADS", mode: this.provider.mode } } }); throw new AppError(400, "Meta authorization failed.", "META_AUTHORIZATION_FAILED"); }
    const safePages = exchanged.pages.map(page => ({ id: page.id, name: page.name, permissions: page.permissions }));
    await prisma.$transaction(async tx => { const connector = await tx.integrationConnector.findFirstOrThrow({ where: connectorWhere(context, connectorId), select: { configuration: true } }); await tx.integrationConnector.update({ where: { id: connectorId }, data: { status: "DRAFT", appSecretEncrypted: encryptSecret(JSON.stringify(exchanged.pages.map(page => ({ id: page.id, token: page.token })))), configuration: { ...(connector.configuration as object), metaSetupMode: "TEST", metaSetupState: "AUTHORIZED", metaAuthorizedPages: safePages, metaTokenExpiresAt: exchanged.expiresAt, metaLeadAuthorizationVerified: false } as Prisma.InputJsonValue, updatedById: context.userId } }); await this.audit(tx, context, connectorId, "META_AUTHORIZATION_COMPLETED", "Meta Lead Ads test authorization completed."); });
    return { returnPath: authorization.returnPath, pages: safePages, mode: this.provider.mode };
  }
  async selectPage(context: Context, connectorId: string, input: MetaPageSelectionInput) {
    const connector = await this.connector(context, connectorId), c = connector.configuration as Config, page = c.metaAuthorizedPages?.find(item => item.id === input.pageId);
    if (!page) throw new AppError(400, "The selected Page was not authorized.", "META_PAGE_UNAVAILABLE");
    const owner = await prisma.integrationConnector.findFirst({ where: { metaPageId: page.id, id: { not: connectorId }, deletedAt: null }, select: { id: true } });
    if (owner) throw new AppError(409, "This Meta Page is already connected.", "META_PAGE_ALREADY_CONNECTED");
    if (!connector.appSecretEncrypted) throw new AppError(409, "Meta authorization must be completed again.", "META_AUTHORIZATION_REQUIRED");
    const tokens = JSON.parse(decryptSecret(connector.appSecretEncrypted)) as Array<{ id: string; token: string }>, tokenPage = tokens.find(item => item.id === page.id);
    if (!tokenPage) throw new AppError(400, "The selected Page was not authorized.", "META_PAGE_UNAVAILABLE");
    const forms = await this.provider.listForms(page.id);
    await prisma.$transaction(async tx => { await tx.integrationConnector.update({ where: { id: connectorId }, data: { metaPageId: page.id, accessTokenEncrypted: encryptSecret(tokenPage.token), appSecretEncrypted: null, credentialsConfiguredAt: new Date(), status: "DRAFT", configuration: { ...c, metaPageName: page.name, metaVerifiedForms: forms, metaLeadAllowedFormIds: [], metaRequiredPermissionsValid: META_LEAD_REQUIRED_PERMISSIONS.every(permission => page.permissions.includes(permission)), metaSetupState: "PAGE_SELECTED" } as Prisma.InputJsonValue, updatedById: context.userId } }); await this.audit(tx, context, connectorId, "META_PAGE_SELECTED", "An authorized synthetic Meta Page was selected."); });
    return { page: { id: page.id, name: page.name }, forms };
  }
  async selectForms(context: Context, connectorId: string, input: MetaFormSelectionInput) { const connector = await this.connector(context, connectorId), c = connector.configuration as Config, allowed = new Set((c.metaVerifiedForms ?? []).map(form => form.id)); if (input.formIds.some(id => !allowed.has(id))) throw new AppError(400, "One or more selected forms are unavailable.", "META_FORM_UNAVAILABLE"); await prisma.$transaction(async tx => { await tx.integrationConnector.update({ where: { id: connectorId }, data: { configuration: { ...c, metaLeadAllowedFormIds: input.formIds, metaSetupState: "FORMS_SELECTED" } as Prisma.InputJsonValue, updatedById: context.userId } }); await this.audit(tx, context, connectorId, "META_FORMS_SELECTED", "Verified synthetic Meta lead forms were selected."); }); return this.status(context, connectorId); }
  async verify(context: Context, connectorId: string) { const connector = await this.connector(context, connectorId), c = connector.configuration as Config; if (c.metaTokenExpiresAt && new Date(c.metaTokenExpiresAt) <= new Date()) throw new AppError(409, "Meta authorization has expired. Reconnect to continue.", "META_AUTHORIZATION_EXPIRED"); if (!connector.metaPageId || !c.metaLeadAllowedFormIds?.length || !c.metaRequiredPermissionsValid) throw new AppError(409, "Complete Page and form selection first.", "META_SETUP_INCOMPLETE"); const subscribed = await this.provider.subscribe(connector.metaPageId), verified = subscribed && await this.provider.verifySubscription(connector.metaPageId), at = new Date().toISOString(); await prisma.$transaction(async tx => { await tx.integrationConnector.update({ where: { id: connectorId }, data: { status: verified ? "DRAFT" : "ERROR", configuration: { ...c, metaSubscriptionVerified: verified, metaLeadAuthorizationVerified: verified, metaLastVerifiedAt: at, metaSetupState: verified ? "READY_TEST" : "ERROR" } as Prisma.InputJsonValue, updatedById: context.userId } }); await this.audit(tx, context, connectorId, "META_VERIFICATION_COMPLETED", verified ? "Synthetic Meta subscription verification passed." : "Synthetic Meta subscription verification failed."); }); return this.status(context, connectorId); }
  async test(context: Context, connectorId: string) { const connector = await this.connector(context, connectorId), c = connector.configuration as Config, formId = c.metaLeadAllowedFormIds?.[0]; if (!connector.metaPageId || !formId || !c.metaSubscriptionVerified) throw new AppError(409, "Verify the connection first.", "META_SETUP_INCOMPLETE"); const lead = await this.provider.syntheticLead(connector.metaPageId, formId), at = new Date().toISOString(); await prisma.$transaction(async tx => { await tx.integrationConnector.update({ where: { id: connectorId }, data: { configuration: { ...c, metaLastTestAt: at, metaSetupState: "READY_TEST" } as Prisma.InputJsonValue, updatedById: context.userId } }); await this.audit(tx, context, connectorId, "META_SYNTHETIC_TEST_COMPLETED", "Synthetic Meta lead validation completed without creating customer data."); }); return { processed: true, synthetic: true, lead: { name: lead.name, email: lead.email }, externalActionPerformed: false }; }
  async activate(context: Context, connectorId: string): Promise<never> { await this.connector(context, connectorId); await prisma.auditEvent.create({ data: { organizationId: context.organizationId, actorType: "USER", actorUserId: context.userId, serviceCode: "AUTOMATION", actionCode: "META_ACTIVATION_BLOCKED", sourceType: "INTEGRATION_CONNECTOR", sourceId: connectorId, summary: "Production activation was blocked because the connector is in Test Mode.", metadata: { provider: "META_LEAD_ADS", mode: this.provider.mode } } }); throw new AppError(409, "Test Mode connectors cannot be activated for production.", "META_PRODUCTION_ACTIVATION_DISABLED"); }
  async reconnect(context: Context, connectorId: string) { const connector = await this.connector(context, connectorId), c = connector.configuration as Config; await prisma.$transaction(async tx => { await tx.integrationConnector.update({ where: { id: connectorId }, data: { status: "DRAFT", metaPageId: null, accessTokenEncrypted: null, appSecretEncrypted: null, credentialsConfiguredAt: null, configuration: { ...c, metaSetupState: "DRAFT", metaLeadAuthorizationVerified: false, metaSubscriptionVerified: false, metaLeadAllowedFormIds: [], metaAuthorizedPages: [] } as Prisma.InputJsonValue, updatedById: context.userId } }); await this.audit(tx, context, connectorId, "META_RECONNECTION_STARTED", "Meta Lead Ads test reconnection started."); }); return this.start(context, connectorId, { returnPath: "/automation" }); }
  async disconnect(context: Context, connectorId: string) { const connector = await this.connector(context, connectorId), c = connector.configuration as Config; let revoked = true; if (connector.metaPageId) revoked = await this.provider.revoke(connector.metaPageId).catch(() => false); await prisma.$transaction(async tx => { await tx.integrationConnector.update({ where: { id: connectorId }, data: { status: revoked ? "PAUSED" : "ERROR", metaPageId: null, accessTokenEncrypted: null, credentialsConfiguredAt: null, configuration: { ...c, metaSetupState: revoked ? "DISCONNECTED" : "ERROR", metaLeadAuthorizationVerified: false, metaSubscriptionVerified: false, metaDisconnectedAt: new Date().toISOString() } as Prisma.InputJsonValue, updatedById: context.userId } }); await this.audit(tx, context, connectorId, "META_DISCONNECTED", revoked ? "Meta Lead Ads test connection disconnected." : "Meta disconnect completed locally; provider revocation failed."); }); return { disconnected: true, providerRevoked: revoked }; }
  private async connector(context: Context, id: string) { const connector = await prisma.integrationConnector.findFirst({ where: connectorWhere(context, id), select: { id: true, status: true, metaPageId: true, appSecretEncrypted: true, configuration: true } }); if (!connector) throw new AppError(404, "Connector was not found.", "CONNECTOR_NOT_FOUND"); return connector; }
  private audit(tx: Prisma.TransactionClient, context: Context, connectorId: string, actionCode: string, summary: string) { return tx.auditEvent.create({ data: { organizationId: context.organizationId, actorType: "USER", actorUserId: context.userId, serviceCode: "AUTOMATION", actionCode, sourceType: "INTEGRATION_CONNECTOR", sourceId: connectorId, summary, metadata: { provider: "META_LEAD_ADS", mode: this.provider.mode } } }); }
}
