import Link from "next/link";
import Image from "next/image";

const outcomes = [
  ["Know what needs attention", "See overdue work, customer follow-ups, cash position and operating risks without assembling reports."],
  ["Keep teams in one rhythm", "Connect customers, sales, projects, people, finance and automations inside one permission-aware workspace."],
  ["Ask with business context", "Ask SATHOS about permitted business data and review every controlled action before it happens."],
] as const;

const services = [
  ["Customers", "Keep customer profiles, conversations, follow-ups and relationship history together."],
  ["Leads & sales", "Turn enquiries into an accountable pipeline with owners, next steps and quotations."],
  ["Projects & tasks", "Plan delivery, assign responsibility and surface overdue work before it becomes a surprise."],
  ["Finance", "Track revenue, expenses, invoices, collections and the facts behind financial health."],
  ["People", "Maintain employee records without confusing them with application accounts or permissions."],
  ["Automation", "Connect approved channels, review pending actions and understand what happened afterward."],
] as const;

const needs = [
  ["I need a clearer sales pipeline", "Capture enquiries, assign owners, track follow-ups and move qualified opportunities toward a sale.", "Customers and sales"],
  ["I need better control of daily work", "Connect projects, tasks, deadlines and ownership so delivery problems become visible earlier.", "Projects and tasks"],
  ["I need to understand business finances", "Review revenue, expenses, invoices and collections from the records your team maintains.", "Finance"],
  ["I need my team to work from the same information", "Give each person access to the services and records needed for their role without opening the entire workspace.", "People and access"],
  ["I need fewer repetitive follow-ups", "Use controlled workflows, approvals and activity history while keeping Test Mode clearly separate from live delivery.", "Automation"],
  ["I need help deciding what to do next", "Ask SATHOS about permitted business data and receive explainable priorities linked back to their sources.", "Ask SATHOS"],
] as const;

const steps = [
  ["Tell us how you operate", "We begin with your real workflows, team structure and the problems creating the most friction."],
  ["Choose the right services", "Your workspace contains only the services that fit the organization, with access matched to each role."],
  ["Set up with guidance", "A SATHOS executive helps prepare the workspace and explains which integrations are live, in Test Mode or unavailable."],
  ["Improve from verified activity", "As real records accumulate, dashboards and briefs become more useful without inventing missing data."],
] as const;

export default function HomePage() {
  return <>
    <section className="site-hero"><div className="site-hero-copy"><span className="site-kicker">Built for what’s next</span><h1>Run your business from one connected operating system.</h1><p>SATHOS brings people, customers, money, work and business intelligence together—so your team can move from scattered updates to clear action.</p><div className="site-actions"><Link className="site-button" href="/contact">Request early access</Link><Link className="site-button secondary" href="/how-it-works">See how it works</Link></div><ul><li>Organization-isolated data</li><li>Permission-aware access</li><li>Human-confirmed actions</li></ul></div><div className="site-hero-art" aria-label="SATHOS connects people, process, AI and growth"><Image src="/brand/sathos-brand-artwork.png" alt="SATHOS symbol with the words People, Process, AI and Growth" width={1280} height={1280} priority /></div></section>
    <section className="site-proof" aria-label="SATHOS principles"><span>One workspace</span><span>Verified business data</span><span>Controlled automation</span><span>Designed for growing teams</span></section>
    <section className="site-section site-needs"><header><span className="site-kicker">Start with what you need</span><h2>What would you like to improve?</h2><p>Choose the business problem that feels familiar. SATHOS brings the related records, responsibilities and next steps into one connected workspace.</p></header><div>{needs.map(([title, copy, area]) => <article key={title}><span>{area}</span><h3>{title}</h3><p>{copy}</p><Link href="/services">See how SATHOS helps →</Link></article>)}</div></section>
    <section className="site-section"><header><span className="site-kicker">Why businesses choose SATHOS</span><h2>Less chasing. More operating.</h2><p>See the state of the business, find the next priority and act through workflows your team can understand.</p></header><div className="site-card-grid">{outcomes.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="site-section site-services"><header><span className="site-kicker">Services that share context</span><h2>Choose what your business needs today.</h2><p>SATHOS is modular. A growing team can begin with customers and finance, then add delivery, people or automation when the underlying process is ready.</p></header><div className="site-service-grid">{services.map(([title, copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p><Link href="/services">Learn more →</Link></article>)}</div></section>
    <section className="site-section site-product"><div><span className="site-kicker">A connected workspace</span><h2>The important parts of your business, working together.</h2><p>Instead of copying updates between separate tools, teams can move from a customer conversation to a project, task, invoice or follow-up while retaining the business context.</p><p>Each person sees only enabled services and permitted records. Owners keep the wider operating picture without giving every teammate unrestricted access.</p><Link className="site-text-link" href="/services">Explore all services →</Link></div><div className="site-product-window"><header><i /><i /><i /><span>Business command centre</span></header><div className="site-product-metrics"><article><small>Revenue</small><strong>Current position</strong><span>Verified from Finance</span></article><article><small>Priorities</small><strong>What needs attention</strong><span>Across enabled services</span></article><article><small>Business health</small><strong>Explainable assessment</strong><span>Based on permitted records</span></article></div><div className="site-product-brief"><span>Today’s brief</span><h3>A focused view of the work that matters now.</h3><p>Review customer follow-ups, delivery risks, cash activity and recent changes from one starting point. Missing or unavailable data stays clearly labelled.</p></div></div></section>
    <section className="site-section site-process"><header><span className="site-kicker">A practical introduction</span><h2>Adopt SATHOS around the way you already work.</h2><p>The goal is not to switch on every module at once. We identify the first useful workflow, establish ownership and expand from verified operating data.</p></header><ol>{steps.map(([title, copy], index) => <li key={title}><span>{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol><Link className="site-text-link" href="/how-it-works">Read the complete onboarding journey →</Link></section>
    <section className="site-section site-agent"><div><span className="site-kicker">Ask SATHOS</span><h2>Business intelligence that respects your boundaries.</h2><p>Ask about business health, customers, finances, projects and priorities. SATHOS uses only the services and records you are allowed to access.</p><ul><li>Read-only answers use verified workspace data.</li><li>Write actions require a clear preview and confirmation.</li><li>Unavailable information is never presented as a verified zero.</li></ul><Link className="site-button secondary light" href="/security">See our safety approach</Link></div><div className="site-agent-dialog"><span>You</span><p>What should I focus on today?</p><span>Ask SATHOS</span><p>Your overdue customer follow-ups and delayed project tasks need review first. Open each source to verify the underlying records.</p><small>Sources and permissions checked</small></div></section>
    <section className="site-section site-fit"><header><span className="site-kicker">Designed for operational clarity</span><h2>Useful when growth creates more coordination than your current tools can handle.</h2></header><div><article><h3>You are following up manually</h3><p>Customer conversations, promised callbacks and sales next steps are difficult to see across the team.</p></article><article><h3>Delivery and money feel disconnected</h3><p>Projects move forward, but invoicing, collections and delivery risks are reviewed in separate places.</p></article><article><h3>Owners depend on status meetings</h3><p>Important context lives with individuals, so understanding what needs attention requires repeated chasing.</p></article><article><h3>You need controlled automation</h3><p>You want fewer repetitive steps while keeping approvals, permissions and an understandable activity trail.</p></article></div></section>
    <section className="site-cta"><span className="site-kicker">Private beta</span><h2>Build a calmer way to run your business.</h2><p>Tell us about your organization, current tools and the workflow causing the most friction. Our team will review the request, discuss fit and help plan an honest setup—without automatically approving an account or charging you.</p><div className="site-actions"><Link className="site-button" href="/contact">Talk to SATHOS</Link><Link href="/login">Already have access? Sign in →</Link></div></section>
  </>;
}
