import { Prisma } from "@prisma/client";import{prisma}from"../../database/prisma.js";import{AppError}from"../../shared/errors/app-error.js";import type{CampaignInput,CampaignLeadInput}from"./marketing.validation.js";
const campaignData=(input:CampaignInput)=>({...input,budget:new Prisma.Decimal(input.budget),spend:new Prisma.Decimal(input.spend)});
export class MarketingService{
 async list(organizationId:string,archived:boolean){const[campaigns,customers,deals]=await Promise.all([prisma.marketingCampaign.findMany({where:{organizationId,deletedAt:archived?{not:null}:null},include:{leads:{include:{customer:{select:{id:true,displayName:true}},deal:{select:{id:true,name:true,stage:true,amount:true,currency:true}}}}},orderBy:{createdAt:"desc"}}),prisma.customer.findMany({where:{organizationId,deletedAt:null},select:{id:true,displayName:true},orderBy:{displayName:"asc"}}),prisma.deal.findMany({where:{organizationId,deletedAt:null},select:{id:true,name:true,stage:true,amount:true,currency:true,customerId:true},orderBy:{name:"asc"}})]);const leads=campaigns.flatMap(c=>c.leads);const revenue=leads.filter(l=>l.status==="CONVERTED"&&l.deal?.stage==="WON").reduce((sum,l)=>sum+Number(l.deal!.amount),0);const spend=campaigns.reduce((sum,c)=>sum+Number(c.spend),0);return{campaigns,customers,deals,metrics:{campaigns:campaigns.length,active:campaigns.filter(c=>c.status==="ACTIVE").length,leads:leads.length,conversions:leads.filter(l=>l.status==="CONVERTED").length,spend,attributedRevenue:revenue,returnOnSpend:spend>0?revenue/spend:0}}}
 create(organizationId:string,userId:string,input:CampaignInput){return prisma.marketingCampaign.create({data:{...campaignData(input),organizationId,createdById:userId,updatedById:userId}})}
 async update(organizationId:string,userId:string,id:string,input:CampaignInput){if((await prisma.marketingCampaign.updateMany({where:{id,organizationId,deletedAt:null},data:{...campaignData(input),updatedById:userId}})).count!==1)throw new AppError(404,"Campaign was not found.","CAMPAIGN_NOT_FOUND")}
 async addLead(organizationId:string,userId:string,campaignId:string,input:CampaignLeadInput){const dealId=input.dealId??null;const[campaign,customer,deal]=await Promise.all([prisma.marketingCampaign.findFirst({where:{id:campaignId,organizationId,deletedAt:null}}),prisma.customer.findFirst({where:{id:input.customerId,organizationId,deletedAt:null}}),dealId?prisma.deal.findFirst({where:{id:dealId,organizationId,customerId:input.customerId,deletedAt:null}}):null]);if(!campaign)throw new AppError(404,"Campaign was not found.","CAMPAIGN_NOT_FOUND");if(!customer)throw new AppError(404,"Customer was not found.","CUSTOMER_NOT_FOUND");if(dealId&&!deal)throw new AppError(400,"The selected deal does not belong to this customer.","INVALID_CAMPAIGN_DEAL");return prisma.campaignLead.upsert({where:{campaignId_customerId:{campaignId,customerId:input.customerId}},update:{dealId,status:input.status,sourceDetail:input.sourceDetail,convertedAt:input.status==="CONVERTED"?new Date():null},create:{organizationId,campaignId,customerId:input.customerId,dealId,status:input.status,sourceDetail:input.sourceDetail,convertedAt:input.status==="CONVERTED"?new Date():null,createdById:userId}})}
 async archive(organizationId:string,userId:string,id:string){if((await prisma.marketingCampaign.updateMany({where:{id,organizationId,deletedAt:null},data:{deletedAt:new Date(),updatedById:userId}})).count!==1)throw new AppError(404,"Campaign was not found.","CAMPAIGN_NOT_FOUND")}
 async restore(organizationId:string,userId:string,id:string){if((await prisma.marketingCampaign.updateMany({where:{id,organizationId,deletedAt:{not:null}},data:{deletedAt:null,updatedById:userId}})).count!==1)throw new AppError(404,"Archived campaign was not found.","CAMPAIGN_NOT_FOUND")}
}
