"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useAuth } from "@/features/auth/auth-context";
import { ApiError } from "@/services/api-client";

type Status = "DRAFT"|"CONFIRMED"|"PROCESSING"|"FULFILLED"|"CANCELED"|"REFUNDED";
interface Customer { id:string;displayName:string }
interface CatalogueItem { id:string;sku:string;name:string;sellingPrice:string;currency:string;taxRate:string }
interface Line { id:string;catalogueItemId:string;skuSnapshot:string;nameSnapshot:string;quantity:string;unitPrice:string;lineTotal:string }
interface Order { id:string;orderNumber:string;status:Status;paymentStatus:string;fulfilmentStatus:string;currency:string;subtotal:string;discount:string;tax:string;shipping:string;total:string;source:string|null;notes:string|null;shippingAddress:string|null;deletedAt:string|null;customer:Customer;items:Line[] }
interface Payload { success:true;data:{orders:Order[];customers:Customer[];catalogueItems:CatalogueItem[];metrics:{totalOrders:number;activeOrders:number;confirmedValue:number;fulfilledValue:number}} }
const empty={customerId:"",orderNumber:"",currency:"INR",discount:0,shipping:0,source:"",notes:"",shippingAddress:"",items:[{catalogueItemId:"",quantity:1}]};
const next:Record<Status,Status[]>={DRAFT:["CONFIRMED","CANCELED"],CONFIRMED:["PROCESSING","CANCELED"],PROCESSING:["FULFILLED","CANCELED"],FULFILLED:["REFUNDED"],CANCELED:[],REFUNDED:[]};

export function OrderWorkspace(){
  const{session,authorizedRequest}=useAuth();const[orders,setOrders]=useState<Order[]>([]);const[customers,setCustomers]=useState<Customer[]>([]);const[catalogue,setCatalogue]=useState<CatalogueItem[]>([]);const[metrics,setMetrics]=useState({totalOrders:0,activeOrders:0,confirmedValue:0,fulfilledValue:0});const[archived,setArchived]=useState(false);const[open,setOpen]=useState(false);const[editing,setEditing]=useState<Order|null>(null);const[form,setForm]=useState(empty);const[error,setError]=useState("");const[saving,setSaving]=useState(false);const canManage=session?.membership.permissions.includes("ORDER_MANAGE")??false;
  const load=useCallback(async()=>{try{const response=await authorizedRequest<Payload>(`/orders?archived=${archived}`);setOrders(response.data.orders);setCustomers(response.data.customers);setCatalogue(response.data.catalogueItems);setMetrics(response.data.metrics);setError("")}catch(reason){setError(reason instanceof ApiError?reason.message:"Unable to load orders.")}},[authorizedRequest,archived]);
  useEffect(()=>{const task=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(task)},[load]);
  const estimate=useMemo(()=>form.items.reduce((sum,line)=>{const item=catalogue.find(i=>i.id===line.catalogueItemId);if(!item)return sum;const base=Number(item.sellingPrice)*line.quantity;return sum+base+base*Number(item.taxRate)/100},0)-form.discount+form.shipping,[form,catalogue]);
  function show(order?:Order){setEditing(order??null);setForm(order?{customerId:order.customer.id,orderNumber:order.orderNumber,currency:order.currency,discount:Number(order.discount),shipping:Number(order.shipping),source:order.source??"",notes:order.notes??"",shippingAddress:order.shippingAddress??"",items:order.items.map(line=>({catalogueItemId:line.catalogueItemId,quantity:Number(line.quantity)}))}: {...empty,orderNumber:`ORD-${String(orders.length+1).padStart(3,"0")}`});setOpen(true);setError("")}
  function setLine(index:number,key:"catalogueItemId"|"quantity",value:string|number){setForm({...form,items:form.items.map((line,i)=>i===index?{...line,[key]:value}:line)})}
  async function save(){setSaving(true);try{await authorizedRequest(editing?`/orders/${editing.id}`:"/orders",{method:editing?"PUT":"POST",body:JSON.stringify(form)});setOpen(false);await load()}catch(reason){setError(reason instanceof ApiError?reason.message:"Unable to save order.")}finally{setSaving(false)}}
  async function status(order:Order,value:Status){try{await authorizedRequest(`/orders/${order.id}/status`,{method:"PATCH",body:JSON.stringify({status:value})});await load()}catch(reason){setError(reason instanceof ApiError?reason.message:"Unable to update order status.")}}
  async function archive(order:Order){await authorizedRequest(order.deletedAt?`/orders/${order.id}/restore`:`/orders/${order.id}`,{method:order.deletedAt?"POST":"DELETE"});setOpen(false);await load()}
  const money=(value:number|string,currency="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency,maximumFractionDigits:2}).format(Number(value));
  return <div className="order-workspace"><header className="project-heading"><div><p>Commerce operations</p><h2>Orders & fulfilment</h2><span>Turn customer commitments into controlled delivery with accurate price snapshots.</span></div>{canManage&&!archived&&<button onClick={()=>show()}>+ New order</button>}</header>{error&&<div className="dashboard-notice error">{error}</div>}<section className="catalogue-metrics"><article><span>Total orders</span><strong>{metrics.totalOrders}</strong></article><article><span>Active</span><strong>{metrics.activeOrders}</strong></article><article><span>Confirmed value</span><strong>{money(metrics.confirmedValue)}</strong></article><article><span>Fulfilled value</span><strong>{money(metrics.fulfilledValue)}</strong></article></section><div className="catalogue-toolbar"><div><span>{orders.length} {archived?"archived":"current"} orders</span></div><button className={archived?"active":""} onClick={()=>setArchived(value=>!value)}>{archived?"Current orders":"Archived"}</button></div>{orders.length===0?<section className="project-empty"><span>◇</span><h3>{archived?"No archived orders":"No orders yet"}</h3><p>Create an order only when a real customer has selected catalogue items.</p>{canManage&&!archived&&<button disabled={!customers.length||!catalogue.length} onClick={()=>show()}>Create first order</button>}{(!customers.length||!catalogue.length)&&!archived&&<small>Add at least one CRM customer and one active catalogue item first.</small>}</section>:<section className="order-list">{orders.map(order=><article key={order.id}><div onClick={()=>order.status==="DRAFT"&&show(order)}><small>{order.orderNumber}</small><h3>{order.customer.displayName}</h3><p>{order.items.length} line item{order.items.length===1?"":"s"} · {order.source||"Direct"}</p></div><div className="order-state"><span className={`order-status ${order.status.toLowerCase()}`}>{order.status}</span><small>{order.fulfilmentStatus.replaceAll("_"," ")}</small></div><strong>{money(order.total,order.currency)}</strong>{canManage&&next[order.status].length>0&&<select value="" onChange={event=>void status(order,event.target.value as Status)}><option value="">Move to…</option>{next[order.status].map(value=><option key={value}>{value}</option>)}</select>}{canManage&&<button onClick={()=>void archive(order)}>{order.deletedAt?"Restore":"Archive"}</button>}</article>)}</section>}
  {open&&<div className="agent-modal"><div className="agent-dialog order-dialog"><header><div><p>Order record</p><h3>{editing?`Edit ${editing.orderNumber}`:"Create order"}</h3></div><button onClick={()=>setOpen(false)}>×</button></header><div className="agent-form-grid"><label><span>Customer</span><select value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}><option value="">Select customer</option>{customers.map(customer=><option key={customer.id} value={customer.id}>{customer.displayName}</option>)}</select></label><label><span>Order number</span><input value={form.orderNumber} onChange={e=>setForm({...form,orderNumber:e.target.value})}/></label><label><span>Currency</span><input maxLength={3} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label><span>Source</span><input placeholder="Website, WhatsApp, store…" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></label></div><div className="order-lines"><header><strong>Line items</strong><button onClick={()=>setForm({...form,items:[...form.items,{catalogueItemId:"",quantity:1}]})}>+ Add line</button></header>{form.items.map((line,index)=><div key={index}><select value={line.catalogueItemId} onChange={e=>setLine(index,"catalogueItemId",e.target.value)}><option value="">Select catalogue item</option>{catalogue.filter(item=>item.currency===form.currency).map(item=><option key={item.id} value={item.id}>{item.sku} — {item.name} ({money(item.sellingPrice,item.currency)})</option>)}</select><input type="number" min="0.001" step="0.001" value={line.quantity} onChange={e=>setLine(index,"quantity",Number(e.target.value))}/><button disabled={form.items.length===1} onClick={()=>setForm({...form,items:form.items.filter((_,i)=>i!==index)})}>×</button></div>)}</div><div className="agent-form-grid"><label><span>Discount</span><input type="number" min="0" value={form.discount} onChange={e=>setForm({...form,discount:Number(e.target.value)})}/></label><label><span>Shipping</span><input type="number" min="0" value={form.shipping} onChange={e=>setForm({...form,shipping:Number(e.target.value)})}/></label></div><label><span>Shipping / fulfilment address</span><textarea rows={2} value={form.shippingAddress} onChange={e=>setForm({...form,shippingAddress:e.target.value})}/></label><label><span>Notes</span><textarea rows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="order-estimate"><span>Estimated total</span><strong>{money(Math.max(0,estimate),form.currency)}</strong><small>The backend verifies catalogue prices, tax and final total.</small></div><footer><button onClick={()=>setOpen(false)}>Cancel</button><button disabled={saving||!form.customerId||!form.orderNumber||form.items.some(line=>!line.catalogueItemId||line.quantity<=0)} onClick={()=>void save()}>{saving?"Saving…":"Save draft"}</button></footer></div></div>}
  </div>
}
