import { Router } from "express";
import { requireActiveContext, requireAuth, requireEnabledService, requirePermission } from "../../middleware/auth.js";
import { validateBody } from "../../middleware/validate.js";
import { archiveAgent, benchmarkAgent, createAgent, getAgent, getAgentSchedule, listAgentRunCentre, listAgentRuns, listAgents, previewCollectionAgent, previewLeadAgent, runCollectionAgent, saveAgentSchedule, updateAgent } from "./agent.controller.js";
import { agentBenchmarkSchema, agentScheduleSchema, collectionAgentPreviewSchema, collectionAgentRunSchema, createAgentSchema, leadAgentPreviewSchema, updateAgentSchema } from "./agent.validation.js";
export const agentRouter = Router();
agentRouter.use(requireAuth, requireActiveContext, requireEnabledService("AUTOMATION"));
agentRouter.get("/", requirePermission("AUTOMATION_VIEW"), listAgents);
agentRouter.get("/runs/centre", requirePermission("AUTOMATION_VIEW"), listAgentRunCentre);
agentRouter.get("/:id", requirePermission("AUTOMATION_VIEW"), getAgent);
agentRouter.get("/:id/runs", requirePermission("AUTOMATION_VIEW"), listAgentRuns);
agentRouter.post("/:id/preview-lead", requirePermission("AUTOMATION_MANAGE"), validateBody(leadAgentPreviewSchema), previewLeadAgent);
agentRouter.post("/:id/preview-collection", requirePermission("AUTOMATION_MANAGE"), validateBody(collectionAgentPreviewSchema), previewCollectionAgent);
agentRouter.post("/:id/run-collection", requirePermission("AUTOMATION_MANAGE"), validateBody(collectionAgentRunSchema), runCollectionAgent);
agentRouter.get("/:id/schedule", requirePermission("AUTOMATION_VIEW"), getAgentSchedule);
agentRouter.put("/:id/schedule", requirePermission("AUTOMATION_MANAGE"), validateBody(agentScheduleSchema), saveAgentSchedule);
agentRouter.post("/:id/benchmark", requirePermission("AUTOMATION_MANAGE"), validateBody(agentBenchmarkSchema), benchmarkAgent);
agentRouter.post("/", requirePermission("AUTOMATION_MANAGE"), validateBody(createAgentSchema), createAgent);
agentRouter.put("/:id", requirePermission("AUTOMATION_MANAGE"), validateBody(updateAgentSchema), updateAgent);
agentRouter.delete("/:id", requirePermission("AUTOMATION_MANAGE"), archiveAgent);
