CREATE TYPE "ProviderApprovalStatus" AS ENUM ('NOT_REQUIRED', 'PENDING_INTERNAL', 'PENDING_CUSTOMER', 'APPROVED', 'REJECTED');
CREATE TYPE "ProviderRequestEventType" AS ENUM ('CREATED', 'ASSIGNED', 'STATUS_CHANGED', 'WORK_CREATED', 'APPROVAL_REQUESTED', 'APPROVAL_DECIDED', 'MESSAGE_SENT', 'COMPLETED');
ALTER TABLE "ProviderServiceRequest" ADD COLUMN "workOrganizationId" UUID, ADD COLUMN "workProjectId" UUID, ADD COLUMN "workTaskId" UUID, ADD COLUMN "responseDueAt" TIMESTAMP(3), ADD COLUMN "resolutionDueAt" TIMESTAMP(3), ADD COLUMN "approvalStatus" "ProviderApprovalStatus" NOT NULL DEFAULT 'NOT_REQUIRED', ADD COLUMN "approvalNote" TEXT, ADD COLUMN "approvalDecidedById" UUID, ADD COLUMN "approvalDecidedAt" TIMESTAMP(3), ADD COLUMN "completionSummary" TEXT, ADD COLUMN "completionEvidenceUrl" TEXT, ADD COLUMN "verificationResult" TEXT;
CREATE TABLE "ProviderRequestEvent" ("id" UUID NOT NULL, "organizationId" UUID NOT NULL, "requestId" UUID NOT NULL, "type" "ProviderRequestEventType" NOT NULL, "summary" TEXT NOT NULL, "customerVisible" BOOLEAN NOT NULL DEFAULT false, "actorUserId" UUID NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ProviderRequestEvent_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ProviderRequestEvent_organizationId_requestId_createdAt_idx" ON "ProviderRequestEvent"("organizationId", "requestId", "createdAt");
ALTER TABLE "ProviderServiceRequest" ADD CONSTRAINT "ProviderServiceRequest_workProjectId_fkey" FOREIGN KEY ("workProjectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProviderServiceRequest" ADD CONSTRAINT "ProviderServiceRequest_workTaskId_fkey" FOREIGN KEY ("workTaskId") REFERENCES "ProjectTask"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProviderRequestEvent" ADD CONSTRAINT "ProviderRequestEvent_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "ProviderServiceRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
UPDATE "ProviderServiceRequest" SET "responseDueAt" = "createdAt" + INTERVAL '8 hours', "resolutionDueAt" = "createdAt" + INTERVAL '72 hours' WHERE "responseDueAt" IS NULL;
