"use client";

import { useEffect, useRef } from "react";
import type { Employee, EmployeeForm, EmployeeStatus, EmploymentType, Member } from "./employee-types";

export function EmployeeDialog({ editing, form, employees, members, canManage, canMembers, saving, error, onChange, onClose, onSave, onArchive }: {
  editing: Employee | null; form: EmployeeForm; employees: Employee[]; members: Member[]; canManage: boolean; canMembers: boolean; saving: boolean; error: string;
  onChange: (form: EmployeeForm) => void; onClose: () => void; onSave: () => void; onArchive: () => void;
}) {
  const dialog = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; document.addEventListener("keydown", close); dialog.current?.querySelector<HTMLElement>("input, select, button")?.focus(); return () => document.removeEventListener("keydown", close); }, [onClose]);
  return <div className="agent-modal people-modal" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div ref={dialog} className="agent-dialog people-dialog" role="dialog" aria-modal="true" aria-labelledby="employee-dialog-title"><header><div><p>Employee record</p><h3 id="employee-dialog-title">{editing ? canManage ? "Update employee" : "Employee details" : "Add employee"}</h3></div><button onClick={onClose} aria-label="Close employee dialog">×</button></header>{error && <div className="dashboard-notice error" role="alert">{error}</div>}<div className="agent-form-grid">
    <label><span>Employee ID <i>Required</i></span><input disabled={!canManage} value={form.employeeNumber} onChange={(e) => onChange({ ...form, employeeNumber: e.target.value })} /></label><label><span>First name <i>Required</i></span><input disabled={!canManage} value={form.firstName} onChange={(e) => onChange({ ...form, firstName: e.target.value })} /></label><label><span>Last name <i>Optional</i></span><input disabled={!canManage} value={form.lastName} onChange={(e) => onChange({ ...form, lastName: e.target.value })} /></label><label><span>Job title <i>Required</i></span><input disabled={!canManage} value={form.jobTitle} onChange={(e) => onChange({ ...form, jobTitle: e.target.value })} /></label><label><span>Department <i>Optional</i></span><input disabled={!canManage} value={form.department} onChange={(e) => onChange({ ...form, department: e.target.value })} /></label><label><span>Employment type</span><select disabled={!canManage} value={form.employmentType} onChange={(e) => onChange({ ...form, employmentType: e.target.value as EmploymentType })}><option value="FULL_TIME">Full time</option><option value="PART_TIME">Part time</option><option value="CONTRACTOR">Contractor</option><option value="INTERN">Intern</option><option value="CONSULTANT">Consultant</option></select></label><label><span>Status</span><select disabled={!canManage} value={form.status} onChange={(e) => onChange({ ...form, status: e.target.value as EmployeeStatus })}><option value="ACTIVE">Active</option><option value="ON_LEAVE">On leave</option><option value="SUSPENDED">Suspended</option><option value="EXITED">Exited</option></select></label><label><span>Start date <i>Required</i></span><input disabled={!canManage} type="date" value={form.startDate} onChange={(e) => onChange({ ...form, startDate: e.target.value })} /></label><label><span>End date <i>Optional</i></span><input disabled={!canManage} type="date" value={form.endDate} onChange={(e) => onChange({ ...form, endDate: e.target.value })} /></label><label><span>Work email <i>Optional</i></span><input disabled={!canManage} type="email" value={form.workEmail} onChange={(e) => onChange({ ...form, workEmail: e.target.value })} /></label><label><span>Work phone <i>Optional</i></span><input disabled={!canManage} value={form.workPhone} onChange={(e) => onChange({ ...form, workPhone: e.target.value })} /></label><label><span>Manager <i>Optional</i></span><select disabled={!canManage} value={form.managerEmployeeId ?? ""} onChange={(e) => onChange({ ...form, managerEmployeeId: e.target.value || null })}><option value="">No manager</option>{employees.filter((employee) => employee.id !== editing?.id && !employee.deletedAt).map((employee) => <option key={employee.id} value={employee.id}>{employee.firstName} {employee.lastName}</option>)}</select></label>
  </div>{canMembers && <label><span>Workspace account <i>Optional</i></span><select disabled={!canManage} value={form.linkedMembershipId ?? ""} onChange={(e) => onChange({ ...form, linkedMembershipId: e.target.value || null })}><option value="">Employee record only — no login account</option>{members.map((member) => <option key={member.id} value={member.id}>{member.user.firstName} {member.user.lastName} ({member.user.email})</option>)}</select><small>Creating an employee does not create a login account.</small></label>}<footer>{editing && canManage && <button onClick={onArchive}>{editing.deletedAt ? "Restore employee" : "Archive employee"}</button>}<button onClick={onClose}>Close</button>{canManage && <button disabled={saving || !form.employeeNumber || !form.firstName || form.jobTitle.length < 2 || !form.startDate} onClick={onSave}>{saving ? "Saving…" : "Save employee"}</button>}</footer></div></div>;
}
