import { prisma } from "../../database/prisma.js";

type Recommendation={key:string;priority:"HIGH"|"MEDIUM"|"LOW";title:string;action:string;evidence:string;view:string};
const change=(current:number,previous:number)=>({current,previous,change:current-previous,changePercent:previous===0?null:(current-previous)/Math.abs(previous)*100});
const clamp=(value:number)=>Math.max(0,Math.min(100,Math.round(value)));

export class AnalysisService{
 async analyze(organizationId:string,permissions:string[],days:number){
  const now=new Date(),currentStart=new Date(now.getTime()-days*86400000),previousStart=new Date(now.getTime()-days*2*86400000);const organization=await prisma.organization.findFirst({where:{id:organizationId,deletedAt:null},select:{currency:true}});const enabled=new Set((await prisma.organizationService.findMany({where:{organizationId,status:"ENABLED",deletedAt:null,service:{status:"ACTIVE",archivedAt:null}},select:{service:{select:{code:true}}}})).map(item=>item.service.code));const can=(service:string,permission:string)=>enabled.has(service)&&permissions.includes(permission);const current={gte:currentStart,lte:now},previous={gte:previousStart,lt:currentStart};
  const[paymentsNow,paymentsPrev,expensesNow,expensesPrev,invoices,dealsNow,dealsPrev,openDeals,customersNow,customersPrev,followUps,ordersNow,ordersPrev,activeOrders,tasks,stock,campaigns,leadsNow,leadsPrev,supportTickets]=await Promise.all([
   can("FINANCE","FINANCE_VIEW")?prisma.payment.findMany({where:{organizationId,deletedAt:null,paidAt:current},select:{amount:true}}):[],can("FINANCE","FINANCE_VIEW")?prisma.payment.findMany({where:{organizationId,deletedAt:null,paidAt:previous},select:{amount:true}}):[],can("FINANCE","FINANCE_VIEW")?prisma.expense.findMany({where:{organizationId,deletedAt:null,status:"RECORDED",expenseDate:current},select:{amount:true}}):[],can("FINANCE","FINANCE_VIEW")?prisma.expense.findMany({where:{organizationId,deletedAt:null,status:"RECORDED",expenseDate:previous},select:{amount:true}}):[],can("FINANCE","FINANCE_VIEW")?prisma.invoice.findMany({where:{organizationId,deletedAt:null,status:{not:"CANCELED"}},include:{payments:{where:{deletedAt:null}}}}):[],
   can("SALES","DEAL_VIEW")?prisma.deal.findMany({where:{organizationId,deletedAt:null,createdAt:current},select:{stage:true,amount:true}}):[],can("SALES","DEAL_VIEW")?prisma.deal.findMany({where:{organizationId,deletedAt:null,createdAt:previous},select:{stage:true,amount:true}}):[],can("SALES","DEAL_VIEW")?prisma.deal.findMany({where:{organizationId,deletedAt:null,stage:{notIn:["WON","LOST"]}},select:{amount:true,probability:true,expectedCloseDate:true}}):[],
   can("CRM","CRM_VIEW")?prisma.customer.count({where:{organizationId,deletedAt:null,createdAt:current}}):0,can("CRM","CRM_VIEW")?prisma.customer.count({where:{organizationId,deletedAt:null,createdAt:previous}}):0,can("CRM","CRM_ACTIVITY_VIEW")?prisma.customerFollowUp.count({where:{organizationId,deletedAt:null,status:"PENDING",dueAt:{lt:now}}}):0,
   can("ORDERS","ORDER_VIEW")?prisma.order.findMany({where:{organizationId,deletedAt:null,createdAt:current},select:{status:true,total:true}}):[],can("ORDERS","ORDER_VIEW")?prisma.order.findMany({where:{organizationId,deletedAt:null,createdAt:previous},select:{status:true,total:true}}):[],can("ORDERS","ORDER_VIEW")?prisma.order.count({where:{organizationId,deletedAt:null,status:{in:["CONFIRMED","PROCESSING"]}}}):0,
   can("PROJECTS","TASK_VIEW")?prisma.projectTask.count({where:{organizationId,deletedAt:null,status:{notIn:["COMPLETED","CANCELED"]},dueDate:{lt:now}}}):0,can("INVENTORY","INVENTORY_VIEW")?prisma.stockLevel.findMany({where:{organizationId},select:{onHand:true,reserved:true,reorderPoint:true}}):[],can("MARKETING","MARKETING_VIEW")?prisma.marketingCampaign.findMany({where:{organizationId,deletedAt:null},select:{spend:true,status:true}}):[],can("MARKETING","MARKETING_VIEW")?prisma.campaignLead.findMany({where:{organizationId,capturedAt:current},include:{deal:{select:{stage:true,amount:true}}}}):[],can("MARKETING","MARKETING_VIEW")?prisma.campaignLead.findMany({where:{organizationId,capturedAt:previous},include:{deal:{select:{stage:true,amount:true}}}}):[],can("SUPPORT","SUPPORT_VIEW")?prisma.supportTicket.findMany({where:{organizationId,deletedAt:null},select:{status:true,responseDueAt:true,resolutionDueAt:true,firstRespondedAt:true,satisfactionRating:true}}):[]]);
  const sum=<T>(items:T[],pick:(item:T)=>number)=>items.reduce((total,item)=>total+pick(item),0);const receivedNow=sum(paymentsNow,item=>Number(item.amount)),receivedPrev=sum(paymentsPrev,item=>Number(item.amount)),expenseNow=sum(expensesNow,item=>Number(item.amount)),expensePrev=sum(expensesPrev,item=>Number(item.amount));const orderNow=sum(ordersNow.filter(item=>!["CANCELED","REFUNDED"].includes(item.status)),item=>Number(item.total)),orderPrev=sum(ordersPrev.filter(item=>!["CANCELED","REFUNDED"].includes(item.status)),item=>Number(item.total));const wonNow=sum(dealsNow.filter(item=>item.stage==="WON"),item=>Number(item.amount)),wonPrev=sum(dealsPrev.filter(item=>item.stage==="WON"),item=>Number(item.amount));const outstanding=sum(invoices,item=>Math.max(0,Number(item.total)-sum(item.payments,payment=>Number(payment.amount))));const pipeline=sum(openDeals,item=>Number(item.amount)),weighted=sum(openDeals,item=>Number(item.amount)*item.probability/100);const lowStock=stock.filter(item=>Number(item.onHand)-Number(item.reserved)<=Number(item.reorderPoint)).length;const marketingSpend=sum(campaigns,item=>Number(item.spend));const attributedNow=sum(leadsNow.filter(item=>item.status==="CONVERTED"&&item.deal?.stage==="WON"),item=>Number(item.deal!.amount));const attributedPrev=sum(leadsPrev.filter(item=>item.status==="CONVERTED"&&item.deal?.stage==="WON"),item=>Number(item.deal!.amount));
  const openSupport=supportTickets.filter(item=>!["RESOLVED","CLOSED"].includes(item.status));const overdueSupport=openSupport.filter(item=>(!item.firstRespondedAt&&item.responseDueAt&&item.responseDueAt<now)||(item.resolutionDueAt&&item.resolutionDueAt<now)).length;const comparisons={receivedRevenue:change(receivedNow,receivedPrev),expenses:change(expenseNow,expensePrev),netCash:change(receivedNow-expenseNow,receivedPrev-expensePrev),wonRevenue:change(wonNow,wonPrev),orderValue:change(orderNow,orderPrev),newCustomers:change(customersNow,customersPrev),marketingConversions:change(leadsNow.filter(item=>item.status==="CONVERTED").length,leadsPrev.filter(item=>item.status==="CONVERTED").length),attributedRevenue:change(attributedNow,attributedPrev)};
  const components:{key:string;label:string;score:number|null;evidence:string;view:string}[]=[];if(can("FINANCE","FINANCE_VIEW")){const score=paymentsNow.length+expensesNow.length+invoices.length===0?null:clamp(50+(receivedNow-expenseNow)/(Math.max(receivedNow,expenseNow,1))*35-outstanding/(Math.max(receivedNow,outstanding,1))*25);components.push({key:"cash",label:"Cash health",score,evidence:score===null?"No finance activity in this period.":`${receivedNow.toFixed(0)} received, ${expenseNow.toFixed(0)} spent, ${outstanding.toFixed(0)} outstanding.`,view:"finance"})}if(can("SALES","DEAL_VIEW")){const closed=dealsNow.filter(item=>["WON","LOST"].includes(item.stage));const winRate=closed.length?closed.filter(item=>item.stage==="WON").length/closed.length:0;components.push({key:"sales",label:"Sales health",score:dealsNow.length+openDeals.length===0?null:clamp(35+winRate*45+(weighted>0?20:0)),evidence:`${openDeals.length} open deals, ${weighted.toFixed(0)} weighted forecast, ${(winRate*100).toFixed(0)}% period win rate.`,view:"sales"})}if(can("CRM","CRM_VIEW"))components.push({key:"customers",label:"Customer health",score:customersNow+customersPrev+followUps===0?null:clamp(75+Math.min(15,customersNow*3)-Math.min(50,followUps*8)),evidence:`${customersNow} new customers and ${followUps} overdue follow-ups.`,view:"crm"});if(can("PROJECTS","TASK_VIEW")||can("ORDERS","ORDER_VIEW"))components.push({key:"delivery",label:"Delivery health",score:tasks+activeOrders===0?100:clamp(100-tasks*10-activeOrders*4),evidence:`${tasks} overdue tasks and ${activeOrders} orders awaiting fulfilment.`,view:tasks?"projects":"orders"});if(can("INVENTORY","INVENTORY_VIEW"))components.push({key:"inventory",label:"Inventory health",score:stock.length===0?null:clamp(100-lowStock/stock.length*100),evidence:`${lowStock} of ${stock.length} stock balances are at or below reorder level.`,view:"inventory"});if(can("MARKETING","MARKETING_VIEW"))components.push({key:"marketing",label:"Marketing health",score:campaigns.length+leadsNow.length===0?null:clamp(30+Math.min(40,leadsNow.filter(item=>item.status==="CONVERTED").length/Math.max(1,leadsNow.length)*100)+(marketingSpend>0&&attributedNow>marketingSpend?30:0)),evidence:`${leadsNow.length} leads, ${leadsNow.filter(item=>item.status==="CONVERTED").length} conversions, ${(marketingSpend?attributedNow/marketingSpend:0).toFixed(2)}x attributed return.`,view:"marketing"});const scored=components.filter(item=>item.score!==null);const overall=scored.length?Math.round(scored.reduce((total,item)=>total+item.score!,0)/scored.length):null;
  const recommendations:Recommendation[]=[];if(outstanding>0)recommendations.push({key:"collect",priority:outstanding>receivedNow?"HIGH":"MEDIUM",title:"Collect outstanding invoices",action:"Review unpaid invoices and schedule customer follow-ups.",evidence:`${outstanding.toFixed(0)} remains outstanding.`,view:"finance"});if(followUps>0)recommendations.push({key:"followups",priority:followUps>=5?"HIGH":"MEDIUM",title:"Clear overdue customer follow-ups",action:"Assign owners and complete the oldest follow-ups first.",evidence:`${followUps} CRM follow-ups are overdue.`,view:"crm"});if(tasks>0)recommendations.push({key:"tasks",priority:tasks>=5?"HIGH":"MEDIUM",title:"Recover delayed project work",action:"Review blockers, owners, and due dates for overdue tasks.",evidence:`${tasks} project tasks are overdue.`,view:"projects"});if(lowStock>0)recommendations.push({key:"stock",priority:"HIGH",title:"Replenish low-stock products",action:"Review inventory balances and record planned receipts.",evidence:`${lowStock} stock balances reached their reorder point.`,view:"inventory"});if(activeOrders>0)recommendations.push({key:"orders",priority:"MEDIUM",title:"Progress confirmed orders",action:"Review confirmed and processing orders to prevent fulfilment delays.",evidence:`${activeOrders} orders are waiting for fulfilment.`,view:"orders"});if(openDeals.length>0&&weighted===0)recommendations.push({key:"pipeline",priority:"MEDIUM",title:"Qualify the sales pipeline",action:"Update probability and next steps for open deals.",evidence:`${openDeals.length} deals are open but weighted forecast is zero.`,view:"sales"});if(marketingSpend>0&&attributedNow===0)recommendations.push({key:"marketing",priority:"MEDIUM",title:"Review marketing attribution",action:"Connect campaign leads to CRM customers and won sales deals.",evidence:`${marketingSpend.toFixed(0)} spend has no attributed won revenue in this period.`,view:"marketing"});
  if(can("SUPPORT","SUPPORT_VIEW"))components.push({key:"support",label:"Support health",score:supportTickets.length===0?null:clamp(100-overdueSupport*15-openSupport.length*3),evidence:`${openSupport.length} open tickets and ${overdueSupport} overdue tickets.`,view:"support"});if(overdueSupport>0)recommendations.push({key:"support",priority:overdueSupport>=5?"HIGH":"MEDIUM",title:"Recover overdue support tickets",action:"Assign owners and respond to the oldest breached tickets first.",evidence:`${overdueSupport} support tickets have missed a response or resolution deadline.`,view:"support"});
  const recordCount=paymentsNow.length+expensesNow.length+dealsNow.length+ordersNow.length+customersNow+leadsNow.length+supportTickets.length;
  const priorityRank={HIGH:0,MEDIUM:1,LOW:2};
  const dataStatus=recordCount===0?"INSUFFICIENT":recordCount<5?"LIMITED":"SUFFICIENT";
  const scoreLabel=overall===null?"Insufficient data":overall>=80?"Strong":overall>=60?"Stable":overall>=40?"Needs attention":"At risk";
  return{currency:organization?.currency??"INR",period:{days,currentStart,currentEnd:now,previousStart,previousEnd:currentStart},dataStatus,recordCount,overallScore:overall,scoreLabel,components,comparisons,recommendations:recommendations.sort((a,b)=>priorityRank[a.priority]-priorityRank[b.priority]),facts:{outstanding,pipeline,weighted,lowStock,overdueFollowUps:followUps,overdueTasks:tasks,activeOrders}};
 }
}
