"use client";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/features/auth/auth-context";
import { ApiError } from "@/services/api-client";
type Recommendation={id:string;serviceCode:string;actionCode:string;title:string;explanation:string;recommendedAction:string;impactSummary:string|null;priority:"LOW"|"MEDIUM"|"HIGH"|"CRITICAL";status:"OPEN"|"EXECUTED"|"DISMISSED"|"RESOLVED";decisionNote:string|null;createdAt:string;decidedBy:{firstName:string;lastName:string|null}|null};
type Payload={success:true;data:{items:Recommendation[];metrics:{open:number;critical:number;executed:number;dismissed:number}}};
export function ActionCentreWorkspace(){const{session,authorizedRequest}=useAuth();const[items,setItems]=useState<Recommendation[]>([]);const[metrics,setMetrics]=useState({open:0,critical:0,executed:0,dismissed:0});const[status,setStatus]=useState("OPEN");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[loading,setLoading]=useState(true);const canDecide=session?.membership.permissions.includes("APPROVAL_DECIDE")??false;
const load=useCallback(async()=>{setLoading(true);try{const response=await authorizedRequest<Payload>("/action-centre");setItems(response.data.items);setMetrics(response.data.metrics);setError("")}catch(reason){setError(reason instanceof ApiError?reason.message:"Unable to calculate business recommendations.")}finally{setLoading(false)}},[authorizedRequest]);useEffect(()=>{const task=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(task)},[load]);
async function decide(item:Recommendation,decision:"EXECUTE"|"DISMISS"){const note=decision==="DISMISS"?window.prompt("Why should this recommendation be dismissed?"):null;if(decision==="DISMISS"&&!note?.trim())return;setError("");setNotice("");try{await authorizedRequest(`/action-centre/${item.id}/decision`,{method:"POST",body:JSON.stringify({decision,note})});setNotice(decision==="EXECUTE"?"Recommended action executed and audited.":"Recommendation dismissed and audited.");await load()}catch(reason){setError(reason instanceof ApiError?reason.message:"Unable to process the recommendation.")}}
const visible=items.filter(item=>!status||item.status===status);return <div className="action-centre-workspace"><header className="project-heading"><div><p>Evidence to action</p><h2>Business Action Centre</h2><span>Rules-based recommendations calculated from your organization’s real operational data.</span></div><button onClick={()=>void load()}>Refresh analysis</button></header>{notice&&<div className="dashboard-notice success">{notice}</div>}{error&&<div className="dashboard-notice error">{error}</div>}<section className="action-metrics"><article><span>Open actions</span><strong>{metrics.open}</strong></article><article className="danger"><span>Critical</span><strong>{metrics.critical}</strong></article><article><span>Executed</span><strong>{metrics.executed}</strong></article><article><span>Dismissed</span><strong>{metrics.dismissed}</strong></article></section><div className="action-toolbar"><div><button className={status==="OPEN"?"active":""} onClick={()=>setStatus("OPEN")}>Open</button><button className={status==="EXECUTED"?"active":""} onClick={()=>setStatus("EXECUTED")}>Executed</button><button className={status==="DISMISSED"?"active":""} onClick={()=>setStatus("DISMISSED")}>Dismissed</button><button className={status===""?"active":""} onClick={()=>setStatus("")}>All</button></div><span>{visible.length} recommendations</span></div><section className="action-list">{loading?<div className="governance-empty">Analyzing real business data…</div>:visible.length===0?<div className="governance-empty"><strong>{status==="OPEN"?"No action required":`No ${status.toLowerCase()} recommendations`}</strong><p>{status==="OPEN"?"B² Brain found no supported risks requiring action right now.":"Decision history will appear here."}</p></div>:visible.map(item=><article key={item.id}><header><div><i className={`risk ${item.priority.toLowerCase()}`}>{item.priority} priority</i><span>{item.serviceCode} · {item.actionCode.replaceAll("_"," ")}</span></div><b className={`approval-status ${item.status.toLowerCase()}`}>{item.status}</b></header><h3>{item.title}</h3><p>{item.explanation}</p><div className="action-proposal"><small>Recommended action</small><strong>{item.recommendedAction}</strong>{item.impactSummary&&<span>{item.impactSummary}</span>}</div><footer><small>Detected {new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.createdAt))}</small>{item.status==="OPEN"&&canDecide&&<div><button onClick={()=>void decide(item,"DISMISS")}>Dismiss</button><button onClick={()=>void decide(item,"EXECUTE")}>Approve & execute</button></div>}{item.decidedBy&&<span>Decided by {item.decidedBy.firstName}{item.decisionNote?` · ${item.decisionNote}`:""}</span>}</footer></article>)}</section></div>}
